import type { BankItem } from './bank';

// Rules for every item (checked mechanically in __tests__/game/bank-content-test.ts, except the
// first, which needs a human): exactly ONE choice is grammatical and natural in that exact sentence;
// context words (yesterday, every day, right now, since 2019...) rule out the others. Four choices
// distinct ignoring case, 1-3 words and at most 16 characters, capitalised when the blank starts the
// sentence; sentences at most 60 characters. American English.
// Bands: 1 basics, 2 everyday tenses, 3 building sentences, 4 getting tricky, 5 tricky usage.
export const ENGLISH_BANK: readonly BankItem[] = [
  // Band 1: a/an, am/is/are, plurals, this/these, have/has
  { id: 'en-1-001', band: 1, sentence: 'I ___ a student.', answer: 'am', wrong: ['is', 'are', 'be'] },
  { id: 'en-1-002', band: 1, sentence: 'She ___ my sister.', answer: 'is', wrong: ['am', 'are', 'be'] },
  { id: 'en-1-003', band: 1, sentence: 'They ___ at school today.', answer: 'are', wrong: ['is', 'am', 'be'] },
  { id: 'en-1-004', band: 1, sentence: 'We ___ very happy.', answer: 'are', wrong: ['is', 'am', 'be'] },
  { id: 'en-1-005', band: 1, sentence: '___ you ready for the test?', answer: 'Are', wrong: ['Is', 'Am', 'Be'] },
  { id: 'en-1-006', band: 1, sentence: '___ she your best friend?', answer: 'Is', wrong: ['Are', 'Am', 'Be'] },
  { id: 'en-1-007', band: 1, sentence: 'The children ___ in the garden.', answer: 'are', wrong: ['is', 'am', 'be'] },
  { id: 'en-1-008', band: 1, sentence: 'My cat ___ black and white.', answer: 'is', wrong: ['are', 'am', 'be'] },
  { id: 'en-1-009', band: 1, sentence: 'The apples ___ red and sweet.', answer: 'are', wrong: ['is', 'am', 'be'] },
  { id: 'en-1-010', band: 1, sentence: 'My name ___ Anna.', answer: 'is', wrong: ['are', 'am', 'be'] },
  { id: 'en-1-011', band: 1, sentence: 'You ___ a good friend.', answer: 'are', wrong: ['is', 'am', 'has'] },
  { id: 'en-1-012', band: 1, sentence: 'This bag ___ heavy.', answer: 'is', wrong: ['are', 'am', 'be'] },
  { id: 'en-1-013', band: 1, sentence: 'I ___ nine years old.', answer: 'am', wrong: ['is', 'are', 'have'] },
  { id: 'en-1-014', band: 1, sentence: 'He ___ ten years old.', answer: 'is', wrong: ['has', 'are', 'am'] },
  { id: 'en-1-015', band: 1, sentence: 'This is ___ apple.', answer: 'an', wrong: ['a', 'two', 'many'] },
  { id: 'en-1-016', band: 1, sentence: 'He wants ___ orange.', answer: 'an', wrong: ['a', 'two', 'these'] },
  { id: 'en-1-017', band: 1, sentence: 'I saw ___ elephant at the zoo.', answer: 'an', wrong: ['a', 'two', 'these'] },
  { id: 'en-1-018', band: 1, sentence: 'She is ___ teacher.', answer: 'a', wrong: ['an', 'two', 'these'] },
  { id: 'en-1-019', band: 1, sentence: 'It is ___ hour until lunch.', answer: 'an', wrong: ['a', 'two', 'these'] },
  { id: 'en-1-020', band: 1, sentence: 'We need ___ new car.', answer: 'a', wrong: ['an', 'two', 'these'] },
  { id: 'en-1-021', band: 1, sentence: 'There is ___ egg in the box.', answer: 'an', wrong: ['a', 'two', 'many'] },
  { id: 'en-1-022', band: 1, sentence: 'My father is ___ honest man.', answer: 'an', wrong: ['a', 'two', 'many'] },
  { id: 'en-1-023', band: 1, sentence: 'She has ___ idea.', answer: 'an', wrong: ['a', 'two', 'many'] },
  { id: 'en-1-024', band: 1, sentence: 'I need ___ umbrella today.', answer: 'an', wrong: ['a', 'two', 'these'] },
  { id: 'en-1-025', band: 1, sentence: 'I have three ___.', answer: 'cats', wrong: ['cat', "cat's", 'a cat'] },
  { id: 'en-1-026', band: 1, sentence: 'There are five ___ in the tree.', answer: 'birds', wrong: ['bird', "bird's", 'a bird'] },
  { id: 'en-1-027', band: 1, sentence: 'Two ___ are playing outside.', answer: 'children', wrong: ['child', 'childs', 'childrens'] },
  { id: 'en-1-028', band: 1, sentence: 'The dentist checked all my ___.', answer: 'teeth', wrong: ['tooth', 'tooths', 'teeths'] },
  { id: 'en-1-029', band: 1, sentence: 'There are three ___ on the table.', answer: 'cups', wrong: ['cup', "cup's", 'a cup'] },
  { id: 'en-1-030', band: 1, sentence: 'Three ___ are waiting at the door.', answer: 'men', wrong: ['man', 'mans', 'a man'] },
  { id: 'en-1-031', band: 1, sentence: 'A spider has eight ___.', answer: 'legs', wrong: ['leg', "leg's", 'a leg'] },
  { id: 'en-1-032', band: 1, sentence: 'Ten ___ ran across the field.', answer: 'mice', wrong: ['mouse', 'mouses', 'mices'] },
  { id: 'en-1-033', band: 1, sentence: '___ is my favorite book.', answer: 'This', wrong: ['These', 'Those', 'They'] },
  { id: 'en-1-034', band: 1, sentence: '___ are my new shoes.', answer: 'These', wrong: ['This', 'That', 'It'] },
  { id: 'en-1-035', band: 1, sentence: 'Look at ___ stars in the sky!', answer: 'those', wrong: ['that', 'this', 'a'] },
  { id: 'en-1-036', band: 1, sentence: 'Is ___ your pencil?', answer: 'this', wrong: ['these', 'those', 'they'] },
  { id: 'en-1-037', band: 1, sentence: 'He ___ a big dog.', answer: 'has', wrong: ['have', 'having', 'haves'] },
  { id: 'en-1-038', band: 1, sentence: 'I ___ two brothers.', answer: 'have', wrong: ['has', 'having', 'haves'] },
  { id: 'en-1-039', band: 1, sentence: 'Our house ___ a red door.', answer: 'has', wrong: ['have', 'having', 'haves'] },
  { id: 'en-1-040', band: 1, sentence: 'My parents ___ a small shop.', answer: 'have', wrong: ['has', 'is', 'haves'] },

  // Band 2: present -s, past -ed, present continuous, do/does, there is/are
  { id: 'en-2-001', band: 2, sentence: 'She ___ to school every day.', answer: 'walks', wrong: ['walk', 'walking', 'to walk'] },
  { id: 'en-2-002', band: 2, sentence: 'He ___ football every Sunday.', answer: 'plays', wrong: ['play', 'playing', 'to play'] },
  { id: 'en-2-003', band: 2, sentence: 'My brother ___ TV after dinner.', answer: 'watches', wrong: ['watch', 'watchs', 'watching'] },
  { id: 'en-2-004', band: 2, sentence: 'The sun ___ in the east.', answer: 'rises', wrong: ['rise', 'rising', 'risen'] },
  { id: 'en-2-005', band: 2, sentence: 'Water ___ at 100 degrees Celsius.', answer: 'boils', wrong: ['boil', 'boiling', 'to boil'] },
  { id: 'en-2-006', band: 2, sentence: 'My parents ___ coffee every morning.', answer: 'drink', wrong: ['drinks', 'drinking', 'to drink'] },
  { id: 'en-2-007', band: 2, sentence: 'My sister ___ her teeth twice a day.', answer: 'brushes', wrong: ['brush', 'brushs', 'brushing'] },
  { id: 'en-2-008', band: 2, sentence: "The shop ___ at nine o'clock every day.", answer: 'opens', wrong: ['open', 'opening', 'to open'] },
  { id: 'en-2-009', band: 2, sentence: 'Birds ___ south every winter.', answer: 'fly', wrong: ['flies', 'flying', 'to fly'] },
  { id: 'en-2-010', band: 2, sentence: 'It ___ a lot here in April.', answer: 'rains', wrong: ['rain', 'raining', 'to rain'] },
  { id: 'en-2-011', band: 2, sentence: 'Yesterday we ___ to the park.', answer: 'walked', wrong: ['walk', 'walks', 'walking'] },
  { id: 'en-2-012', band: 2, sentence: 'Last night I ___ my homework.', answer: 'finished', wrong: ['finish', 'finishes', 'finishing'] },
  { id: 'en-2-013', band: 2, sentence: 'They ___ a movie two days ago.', answer: 'watched', wrong: ['watch', 'watches', 'watching'] },
  { id: 'en-2-014', band: 2, sentence: 'She ___ the piano last weekend.', answer: 'played', wrong: ['play', 'plays', 'playing'] },
  { id: 'en-2-015', band: 2, sentence: 'We ___ in London in 2015.', answer: 'lived', wrong: ['live', 'lives', 'living'] },
  { id: 'en-2-016', band: 2, sentence: 'He ___ the door a minute ago.', answer: 'opened', wrong: ['open', 'opens', 'opening'] },
  { id: 'en-2-017', band: 2, sentence: 'We ___ the house last Saturday.', answer: 'cleaned', wrong: ['clean', 'cleans', 'cleaning'] },
  { id: 'en-2-018', band: 2, sentence: 'I ___ my grandmother last Sunday.', answer: 'visited', wrong: ['visit', 'visits', 'visiting'] },
  { id: 'en-2-019', band: 2, sentence: 'The train ___ at the station ten minutes ago.', answer: 'arrived', wrong: ['arrive', 'arrives', 'arriving'] },
  { id: 'en-2-020', band: 2, sentence: 'Listen! The baby ___.', answer: 'is crying', wrong: ['cry', 'cries', 'crying'] },
  { id: 'en-2-021', band: 2, sentence: 'Look! It ___ outside.', answer: 'is snowing', wrong: ['snow', 'snows', 'snowing'] },
  { id: 'en-2-022', band: 2, sentence: 'Right now, I ___ a book.', answer: 'am reading', wrong: ['read', 'reads', 'reading'] },
  { id: 'en-2-023', band: 2, sentence: 'The children ___ in the pool at the moment.', answer: 'are swimming', wrong: ['swim', 'swims', 'swimming'] },
  { id: 'en-2-024', band: 2, sentence: 'Please be quiet. Dad ___.', answer: 'is sleeping', wrong: ['sleep', 'sleeps', 'sleeping'] },
  { id: 'en-2-025', band: 2, sentence: 'Mom ___ dinner right now.', answer: 'is cooking', wrong: ['cook', 'cooks', 'cooking'] },
  { id: 'en-2-026', band: 2, sentence: 'We ___ our lunch at the moment.', answer: 'are eating', wrong: ['eat', 'eats', 'eating'] },
  { id: 'en-2-027', band: 2, sentence: '___ you like pizza?', answer: 'Do', wrong: ['Does', 'Is', 'Are'] },
  { id: 'en-2-028', band: 2, sentence: '___ she speak French?', answer: 'Does', wrong: ['Do', 'Is', 'Are'] },
  { id: 'en-2-029', band: 2, sentence: 'Where ___ your cousins live?', answer: 'do', wrong: ['does', 'is', 'are'] },
  { id: 'en-2-030', band: 2, sentence: 'What time ___ the bus leave?', answer: 'does', wrong: ['do', 'is', 'are'] },
  { id: 'en-2-031', band: 2, sentence: 'I ___ like spinach.', answer: "don't", wrong: ["doesn't", "isn't", "aren't"] },
  { id: 'en-2-032', band: 2, sentence: 'He ___ eat meat.', answer: "doesn't", wrong: ["don't", "isn't", "aren't"] },
  { id: 'en-2-033', band: 2, sentence: '___ your dog bark at night?', answer: 'Does', wrong: ['Do', 'Is', 'Are'] },
  { id: 'en-2-034', band: 2, sentence: 'Why ___ he always late?', answer: 'is', wrong: ['does', 'do', 'are'] },
  { id: 'en-2-035', band: 2, sentence: 'There ___ a cat on the roof.', answer: 'is', wrong: ['are', 'am', 'be'] },
  { id: 'en-2-036', band: 2, sentence: 'There ___ many books on the shelf.', answer: 'are', wrong: ['is', 'am', 'be'] },
  { id: 'en-2-037', band: 2, sentence: 'There ___ some milk in the fridge.', answer: 'is', wrong: ['are', 'am', 'be'] },
  { id: 'en-2-038', band: 2, sentence: '___ there any eggs left?', answer: 'Are', wrong: ['Is', 'Am', 'Do'] },
  { id: 'en-2-039', band: 2, sentence: 'How many students ___ there in your class?', answer: 'are', wrong: ['is', 'am', 'do'] },
  { id: 'en-2-040', band: 2, sentence: 'They ___ basketball on Fridays.', answer: 'play', wrong: ['plays', 'playing', 'to play'] },

  // Band 3: in/on/at, irregular past, comparatives/superlatives, much/many, some/any
  { id: 'en-3-001', band: 3, sentence: 'My birthday is ___ June.', answer: 'in', wrong: ['on', 'at', 'by'] },
  { id: 'en-3-002', band: 3, sentence: 'The party is ___ Saturday.', answer: 'on', wrong: ['in', 'at', 'to'] },
  { id: 'en-3-003', band: 3, sentence: "The movie starts ___ seven o'clock.", answer: 'at', wrong: ['in', 'on', 'to'] },
  { id: 'en-3-004', band: 3, sentence: 'I was born ___ 2010.', answer: 'in', wrong: ['on', 'at', 'to'] },
  { id: 'en-3-005', band: 3, sentence: 'There is a picture ___ the wall.', answer: 'on', wrong: ['in', 'at', 'to'] },
  { id: 'en-3-006', band: 3, sentence: 'She lives ___ Paris.', answer: 'in', wrong: ['on', 'at', 'to'] },
  { id: 'en-3-007', band: 3, sentence: "I'll meet you ___ the bus stop.", answer: 'at', wrong: ['in', 'on', 'to'] },
  { id: 'en-3-008', band: 3, sentence: 'I usually read ___ night.', answer: 'at', wrong: ['in', 'on', 'to'] },
  { id: 'en-3-009', band: 3, sentence: 'School starts ___ September.', answer: 'in', wrong: ['on', 'at', 'to'] },
  { id: 'en-3-010', band: 3, sentence: 'My dad is still ___ bed.', answer: 'in', wrong: ['on', 'at', 'to'] },
  { id: 'en-3-011', band: 3, sentence: 'She is not ___ home right now.', answer: 'at', wrong: ['in', 'on', 'to'] },
  { id: 'en-3-012', band: 3, sentence: 'We watched the game ___ TV.', answer: 'on', wrong: ['in', 'at', 'to'] },
  { id: 'en-3-013', band: 3, sentence: 'Yesterday I ___ a letter to my aunt.', answer: 'wrote', wrong: ['write', 'writed', 'written'] },
  { id: 'en-3-014', band: 3, sentence: 'We ___ to the beach last summer.', answer: 'went', wrong: ['go', 'goed', 'gone'] },
  { id: 'en-3-015', band: 3, sentence: 'She ___ a new dress yesterday.', answer: 'bought', wrong: ['buy', 'buyed', 'buys'] },
  { id: 'en-3-016', band: 3, sentence: 'He ___ his wallet on the bus last week.', answer: 'lost', wrong: ['lose', 'losed', 'loses'] },
  { id: 'en-3-017', band: 3, sentence: 'I ___ a strange noise last night.', answer: 'heard', wrong: ['hear', 'heared', 'hears'] },
  { id: 'en-3-018', band: 3, sentence: 'They ___ the match two days ago.', answer: 'won', wrong: ['win', 'winned', 'wins'] },
  { id: 'en-3-019', band: 3, sentence: 'My mom ___ a delicious cake yesterday.', answer: 'made', wrong: ['make', 'maked', 'makes'] },
  { id: 'en-3-020', band: 3, sentence: 'The children ___ milk with breakfast this morning.', answer: 'drank', wrong: ['drink', 'drinked', 'drinks'] },
  { id: 'en-3-021', band: 3, sentence: 'I ___ my friend at the mall yesterday.', answer: 'saw', wrong: ['see', 'seed', 'seen'] },
  { id: 'en-3-022', band: 3, sentence: 'Last year we ___ a trip to Japan.', answer: 'took', wrong: ['take', 'taked', 'takes'] },
  { id: 'en-3-023', band: 3, sentence: 'He ___ his leg when he fell off his bike.', answer: 'broke', wrong: ['break', 'breaked', 'broken'] },
  { id: 'en-3-024', band: 3, sentence: 'She ___ me a funny story yesterday.', answer: 'told', wrong: ['tell', 'telled', 'tells'] },
  { id: 'en-3-025', band: 3, sentence: 'An elephant is ___ than a horse.', answer: 'bigger', wrong: ['big', 'biggest', 'more big'] },
  { id: 'en-3-026', band: 3, sentence: 'My sister is ___ than me.', answer: 'taller', wrong: ['tall', 'tallest', 'more tall'] },
  { id: 'en-3-027', band: 3, sentence: 'This is the ___ day of the year.', answer: 'hottest', wrong: ['hot', 'hotter', 'most hot'] },
  { id: 'en-3-028', band: 3, sentence: 'Mount Everest is the ___ mountain in the world.', answer: 'highest', wrong: ['high', 'higher', 'most high'] },
  { id: 'en-3-029', band: 3, sentence: 'This test is ___ than the last one.', answer: 'easier', wrong: ['easy', 'easiest', 'more easy'] },
  { id: 'en-3-030', band: 3, sentence: 'She is the ___ student in our class.', answer: 'best', wrong: ['good', 'most good', 'goodest'] },
  { id: 'en-3-031', band: 3, sentence: 'My cold is ___ today than yesterday.', answer: 'worse', wrong: ['bad', 'worst', 'badder'] },
  { id: 'en-3-032', band: 3, sentence: 'This book is ___ than that one.', answer: 'more interesting', wrong: ['interesting', 'most interesting', 'interestinger'] },
  { id: 'en-3-033', band: 3, sentence: 'How ___ water do you drink every day?', answer: 'much', wrong: ['many', 'lot', 'few'] },
  { id: 'en-3-034', band: 3, sentence: 'How ___ brothers do you have?', answer: 'many', wrong: ['much', 'lot', 'a lot'] },
  { id: 'en-3-035', band: 3, sentence: "There isn't ___ sugar left.", answer: 'much', wrong: ['many', 'lots', 'few'] },
  { id: 'en-3-036', band: 3, sentence: "We don't have ___ friends here yet.", answer: 'many', wrong: ['much', 'lot', 'a lot'] },
  { id: 'en-3-037', band: 3, sentence: 'I bought ___ apples at the market.', answer: 'some', wrong: ['any', 'much', 'a'] },
  { id: 'en-3-038', band: 3, sentence: "There aren't ___ cookies left.", answer: 'any', wrong: ['some', 'much', 'a'] },
  { id: 'en-3-039', band: 3, sentence: "She doesn't have ___ brothers or sisters.", answer: 'any', wrong: ['some', 'much', 'a'] },
  { id: 'en-3-040', band: 3, sentence: 'I need ___ help with my homework.', answer: 'some', wrong: ['any', 'many', 'a'] },

  // Band 4: since/for, present perfect, adjective vs adverb, I/me, who/which/whose
  { id: 'en-4-001', band: 4, sentence: 'She has lived here ___ 2019.', answer: 'since', wrong: ['for', 'from', 'during'] },
  { id: 'en-4-002', band: 4, sentence: 'I have known him ___ ten years.', answer: 'for', wrong: ['since', 'from', 'during'] },
  { id: 'en-4-003', band: 4, sentence: 'We have been waiting ___ two hours.', answer: 'for', wrong: ['since', 'from', 'at'] },
  { id: 'en-4-004', band: 4, sentence: 'He has worked at the bank ___ last June.', answer: 'since', wrong: ['for', 'from', 'during'] },
  { id: 'en-4-005', band: 4, sentence: 'They have been friends ___ they were children.', answer: 'since', wrong: ['for', 'from', 'during'] },
  { id: 'en-4-006', band: 4, sentence: 'I have lived in this house ___ I was born.', answer: 'since', wrong: ['for', 'from', 'when'] },
  { id: 'en-4-007', band: 4, sentence: "We've been here ___ nine o'clock.", answer: 'since', wrong: ['for', 'from', 'at'] },
  { id: 'en-4-008', band: 4, sentence: "I've been learning English ___ three years.", answer: 'for', wrong: ['since', 'from', 'during'] },
  { id: 'en-4-009', band: 4, sentence: 'I have ___ this movie three times.', answer: 'seen', wrong: ['saw', 'see', 'seeing'] },
  { id: 'en-4-010', band: 4, sentence: 'She has already ___ her lunch.', answer: 'eaten', wrong: ['ate', 'eat', 'eating'] },
  { id: 'en-4-011', band: 4, sentence: 'Have you ever ___ to Canada?', answer: 'been', wrong: ['was', 'went', 'go'] },
  { id: 'en-4-012', band: 4, sentence: 'We ___ just finished our homework.', answer: 'have', wrong: ['has', 'are', 'is'] },
  { id: 'en-4-013', band: 4, sentence: 'He ___ never been on a plane.', answer: 'has', wrong: ['have', 'is', 'was'] },
  { id: 'en-4-014', band: 4, sentence: 'I ___ my keys. Can you help me find them?', answer: 'have lost', wrong: ['lose', 'loses', 'losing'] },
  { id: 'en-4-015', band: 4, sentence: 'She has ___ in this city all her life.', answer: 'lived', wrong: ['live', 'living', 'lives'] },
  { id: 'en-4-016', band: 4, sentence: 'I ___ finished the book yet.', answer: "haven't", wrong: ["hasn't", "don't", "isn't"] },
  { id: 'en-4-017', band: 4, sentence: 'Has she ___ her homework yet?', answer: 'done', wrong: ['did', 'do', 'doing'] },
  { id: 'en-4-018', band: 4, sentence: "They have ___ to the store. They'll be back soon.", answer: 'gone', wrong: ['been', 'went', 'go'] },
  { id: 'en-4-019', band: 4, sentence: 'He drives very ___.', answer: 'carefully', wrong: ['careful', 'care', 'carefulness'] },
  { id: 'en-4-020', band: 4, sentence: 'She sings ___.', answer: 'beautifully', wrong: ['beautiful', 'beauty', 'more beautiful'] },
  { id: 'en-4-021', band: 4, sentence: 'The test was ___ for me.', answer: 'easy', wrong: ['easily', 'ease', 'easing'] },
  { id: 'en-4-022', band: 4, sentence: 'He speaks English very ___.', answer: 'well', wrong: ['good', 'goodly', 'best'] },
  { id: 'en-4-023', band: 4, sentence: 'The baby smiled ___.', answer: 'happily', wrong: ['happy', 'happiness', 'happiest'] },
  { id: 'en-4-024', band: 4, sentence: 'This soup tastes ___.', answer: 'delicious', wrong: ['deliciously', 'deliciousness', 'more deliciously'] },
  { id: 'en-4-025', band: 4, sentence: 'You look ___ today.', answer: 'tired', wrong: ['tiredly', 'tire', 'tiredness'] },
  { id: 'en-4-026', band: 4, sentence: 'She sang the song ___.', answer: 'perfectly', wrong: ['perfect', 'perfection', 'perfected'] },
  { id: 'en-4-027', band: 4, sentence: 'The man shouted ___ at the driver.', answer: 'angrily', wrong: ['angry', 'anger', 'angrier'] },
  { id: 'en-4-028', band: 4, sentence: 'It was a ___ day, so we went to the beach.', answer: 'sunny', wrong: ['sunnily', 'sun', 'suns'] },
  { id: 'en-4-029', band: 4, sentence: 'My mom and ___ went shopping.', answer: 'I', wrong: ['me', 'myself', 'mine'] },
  { id: 'en-4-030', band: 4, sentence: 'The teacher gave the books to Sam and ___.', answer: 'me', wrong: ['I', 'my', 'mine'] },
  { id: 'en-4-031', band: 4, sentence: 'Tom and ___ are going to the park.', answer: 'I', wrong: ['me', 'my', 'mine'] },
  { id: 'en-4-032', band: 4, sentence: 'Can you help ___ with this box?', answer: 'me', wrong: ['I', 'my', 'mine'] },
  { id: 'en-4-033', band: 4, sentence: 'The man ___ lives next door is a doctor.', answer: 'who', wrong: ['which', 'whose', 'whom'] },
  { id: 'en-4-034', band: 4, sentence: 'This is the book ___ I told you about.', answer: 'which', wrong: ['who', 'whose', 'whom'] },
  { id: 'en-4-035', band: 4, sentence: 'I have a friend ___ speaks four languages.', answer: 'who', wrong: ['which', 'whose', 'whom'] },
  { id: 'en-4-036', band: 4, sentence: 'The cake ___ you made was delicious.', answer: 'which', wrong: ['who', 'whose', 'whom'] },
  { id: 'en-4-037', band: 4, sentence: 'She is the girl ___ bag was stolen.', answer: 'whose', wrong: ['who', 'which', "who's"] },
  { id: 'en-4-038', band: 4, sentence: 'Do you know the woman ___ owns this shop?', answer: 'who', wrong: ['which', 'whose', 'whom'] },
  { id: 'en-4-039', band: 4, sentence: 'We stayed at a hotel ___ was near the beach.', answer: 'which', wrong: ['who', 'whose', 'where'] },
  { id: 'en-4-040', band: 4, sentence: 'This is the house ___ my grandparents built.', answer: 'which', wrong: ['who', 'whose', 'whom'] },

  // Band 5: their/there/they're, your/you're, its/it's, then/than, fewer/less, who/whom, affect/effect,
  // lie/lay, to/too/two, lose/loose, accept/except, quiet/quite, should have, between you and me, if I were
  { id: 'en-5-001', band: 5, sentence: '___ going to be late.', answer: "They're", wrong: ['Their', 'There', 'Theirs'] },
  { id: 'en-5-002', band: 5, sentence: 'The students forgot ___ books.', answer: 'their', wrong: ['there', "they're", 'theirs'] },
  { id: 'en-5-003', band: 5, sentence: 'Put the box over ___.', answer: 'there', wrong: ['their', "they're", "there's"] },
  { id: 'en-5-004', band: 5, sentence: '___ are three cats in the garden.', answer: 'There', wrong: ['Their', "They're", 'Theirs'] },
  { id: 'en-5-005', band: 5, sentence: 'Is this ___ jacket?', answer: 'your', wrong: ["you're", 'yours', 'you'] },
  { id: 'en-5-006', band: 5, sentence: '___ my best friend.', answer: "You're", wrong: ['Your', 'Yours', 'You'] },
  { id: 'en-5-007', band: 5, sentence: 'I think ___ right about that.', answer: "you're", wrong: ['your', 'yours', 'you'] },
  { id: 'en-5-008', band: 5, sentence: 'The dog wagged ___ tail.', answer: 'its', wrong: ["it's", 'it', "its'"] },
  { id: 'en-5-009', band: 5, sentence: '___ raining again today.', answer: "It's", wrong: ['Its', 'It', "Its'"] },
  { id: 'en-5-010', band: 5, sentence: 'The company changed ___ name last year.', answer: 'its', wrong: ["it's", 'it', "its'"] },
  { id: 'en-5-011', band: 5, sentence: 'I think ___ time to go home.', answer: "it's", wrong: ['its', 'it', "its'"] },
  { id: 'en-5-012', band: 5, sentence: 'She is taller ___ her brother.', answer: 'than', wrong: ['then', 'that', 'as'] },
  { id: 'en-5-013', band: 5, sentence: 'We ate dinner, and ___ we watched a movie.', answer: 'then', wrong: ['than', 'that', 'them'] },
  { id: 'en-5-014', band: 5, sentence: 'This box is heavier ___ that one.', answer: 'than', wrong: ['then', 'that', 'as'] },
  { id: 'en-5-015', band: 5, sentence: 'First mix the flour, ___ add the eggs.', answer: 'then', wrong: ['than', 'that', 'them'] },
  { id: 'en-5-016', band: 5, sentence: 'There are ___ people here than yesterday.', answer: 'fewer', wrong: ['less', 'little', 'lesser'] },
  { id: 'en-5-017', band: 5, sentence: 'I drink ___ coffee than I used to.', answer: 'less', wrong: ['fewer', 'lesser', 'little'] },
  { id: 'en-5-018', band: 5, sentence: 'We had ___ problems this year than last year.', answer: 'fewer', wrong: ['less', 'little', 'lesser'] },
  { id: 'en-5-019', band: 5, sentence: 'With ___ did you go to the movies?', answer: 'whom', wrong: ['who', "who's", 'whose'] },
  { id: 'en-5-020', band: 5, sentence: 'To ___ should I send this letter?', answer: 'whom', wrong: ['who', 'whose', "who's"] },
  { id: 'en-5-021', band: 5, sentence: '___ bag is this?', answer: 'Whose', wrong: ["Who's", 'Who', 'Whom'] },
  { id: 'en-5-022', band: 5, sentence: '___ coming to dinner tonight?', answer: "Who's", wrong: ['Whose', 'Who', 'Whom'] },
  { id: 'en-5-023', band: 5, sentence: 'The weather can ___ your mood.', answer: 'affect', wrong: ['effect', 'affects', 'effects'] },
  { id: 'en-5-024', band: 5, sentence: 'The new rule had a big ___ on students.', answer: 'effect', wrong: ['affect', 'effects', 'affects'] },
  { id: 'en-5-025', band: 5, sentence: "Loud music doesn't ___ my sleep.", answer: 'affect', wrong: ['effect', 'affects', 'effects'] },
  { id: 'en-5-026', band: 5, sentence: 'Every afternoon, the cat likes to ___ in the sun.', answer: 'lie', wrong: ['lay', 'lays', 'laid'] },
  { id: 'en-5-027', band: 5, sentence: 'Please ___ the book on the table.', answer: 'lay', wrong: ['lie', 'lies', 'laid'] },
  { id: 'en-5-028', band: 5, sentence: 'I ate ___ much cake at the party.', answer: 'too', wrong: ['to', 'two', 'toe'] },
  { id: 'en-5-029', band: 5, sentence: 'We have ___ dogs and a cat.', answer: 'two', wrong: ['too', 'to', 'tow'] },
  { id: 'en-5-030', band: 5, sentence: 'She wants to go ___ the library.', answer: 'to', wrong: ['too', 'two', 'tow'] },
  { id: 'en-5-031', band: 5, sentence: 'These shoes are too ___ for me.', answer: 'loose', wrong: ['lose', 'loss', 'lost'] },
  { id: 'en-5-032', band: 5, sentence: "Don't ___ your ticket!", answer: 'lose', wrong: ['loose', 'loss', 'lost'] },
  { id: 'en-5-033', band: 5, sentence: 'Everyone came ___ Tom, who was sick.', answer: 'except', wrong: ['accept', 'expect', 'excepted'] },
  { id: 'en-5-034', band: 5, sentence: 'Please ___ my apology.', answer: 'accept', wrong: ['except', 'excepts', 'accepts'] },
  { id: 'en-5-035', band: 5, sentence: 'The library is very ___.', answer: 'quiet', wrong: ['quite', 'quit', 'quietly'] },
  { id: 'en-5-036', band: 5, sentence: 'The movie was ___ good.', answer: 'quite', wrong: ['quiet', 'quit', 'quitely'] },
  { id: 'en-5-037', band: 5, sentence: 'You ___ told me about the party!', answer: 'should have', wrong: ['should of', 'should had', 'should has'] },
  { id: 'en-5-038', band: 5, sentence: 'We ___ left earlier to avoid the traffic.', answer: 'could have', wrong: ['could of', 'could had', 'could has'] },
  { id: 'en-5-039', band: 5, sentence: "Between you and ___, I don't like the new rules.", answer: 'me', wrong: ['I', 'myself', 'mine'] },
  { id: 'en-5-040', band: 5, sentence: 'If I ___ you, I would study harder.', answer: 'were', wrong: ['was', 'am', 'be'] },
];
