import type { BankItem } from './bank';

// Rules for every item.
// A person must check these: exactly ONE choice is true in that exact sentence, and the wrong choices
// are clearly false but from the same category (cities with cities, rivers with rivers); true as
// written, qualified where needed ("above sea level", "hot desert"); nothing in flux (capitals that
// are being moved, shared or disputed; disputed borders; recent renames and competing spellings;
// populations) and no contested records (the longest river, how many continents or oceans); for a
// capital, the wrong choices are real cities of that country and never another of its capitals;
// common English names, with accents where the name normally carries them (Brasília), and "the" in
// the sentence, not in the choice; politically neutral and suitable for all ages. Numbers as digits,
// metric units, American spelling.
// __tests__/game/bank-content-test.ts checks these: four choices distinct ignoring case, 1-3 words and
// at most 16 characters, capitalised when the blank starts the sentence; sentences at most 60
// characters.
// Bands: 1 Earth and maps, 2 famous countries, capitals and landmarks, 3 rivers, mountains, deserts
// and landforms, 4 harder capitals and map skills, 5 tricky facts.
export const GEOGRAPHY_BANK: readonly BankItem[] = [
  // Band 1: continents and oceans, the poles, deserts and islands, maps and globes, compass directions, simple landforms
  { id: 'geo-1-001', band: 1, sentence: 'The largest ocean is the ___.', answer: 'Pacific', wrong: ['Atlantic', 'Indian', 'Arctic'] },
  { id: 'geo-1-002', band: 1, sentence: 'The largest continent is ___.', answer: 'Asia', wrong: ['Africa', 'Europe', 'Antarctica'] },
  { id: 'geo-1-003', band: 1, sentence: 'The coldest continent is ___.', answer: 'Antarctica', wrong: ['Europe', 'Asia', 'North America'] },
  { id: 'geo-1-004', band: 1, sentence: 'The South Pole is on the continent of ___.', answer: 'Antarctica', wrong: ['Africa', 'Australia', 'Asia'] },
  { id: 'geo-1-005', band: 1, sentence: 'The North Pole is in the ___ Ocean.', answer: 'Arctic', wrong: ['Pacific', 'Atlantic', 'Indian'] },
  { id: 'geo-1-006', band: 1, sentence: 'The ___ Ocean lies between Africa and South America.', answer: 'Atlantic', wrong: ['Pacific', 'Indian', 'Arctic'] },
  { id: 'geo-1-007', band: 1, sentence: 'The ___ Ocean lies between Africa and Australia.', answer: 'Indian', wrong: ['Atlantic', 'Pacific', 'Arctic'] },
  { id: 'geo-1-008', band: 1, sentence: 'The Pacific and the Atlantic are both ___.', answer: 'oceans', wrong: ['continents', 'rivers', 'lakes'] },
  { id: 'geo-1-009', band: 1, sentence: 'Europe and Asia are both ___.', answer: 'continents', wrong: ['countries', 'oceans', 'cities'] },
  { id: 'geo-1-010', band: 1, sentence: 'Africa is a ___.', answer: 'continent', wrong: ['country', 'city', 'island'] },
  { id: 'geo-1-011', band: 1, sentence: 'The continent south of Europe is ___.', answer: 'Africa', wrong: ['Asia', 'Australia', 'North America'] },
  { id: 'geo-1-012', band: 1, sentence: 'The Sahara is a hot desert in ___.', answer: 'Africa', wrong: ['Asia', 'Australia', 'Europe'] },
  { id: 'geo-1-013', band: 1, sentence: 'A very dry place with little rain is a ___.', answer: 'desert', wrong: ['jungle', 'swamp', 'lake'] },
  { id: 'geo-1-014', band: 1, sentence: 'An island is land surrounded by ___.', answer: 'water', wrong: ['sand', 'mountains', 'forest'] },
  { id: 'geo-1-015', band: 1, sentence: 'A ___ is water with land all around it.', answer: 'lake', wrong: ['river', 'waterfall', 'glacier'] },
  { id: 'geo-1-016', band: 1, sentence: 'Ocean water is ___.', answer: 'salty', wrong: ['fresh', 'sweet', 'fizzy'] },
  { id: 'geo-1-017', band: 1, sentence: "There is more ___ than land on Earth's surface.", answer: 'water', wrong: ['ice', 'sand', 'forest'] },
  { id: 'geo-1-018', band: 1, sentence: 'A ___ is a round model of Earth.', answer: 'globe', wrong: ['map', 'compass', 'chart'] },
  { id: 'geo-1-019', band: 1, sentence: 'A ___ is a drawing of a place seen from above.', answer: 'map', wrong: ['globe', 'compass', 'telescope'] },
  { id: 'geo-1-020', band: 1, sentence: 'A book of maps is called an ___.', answer: 'atlas', wrong: ['album', 'index', 'essay'] },
  { id: 'geo-1-021', band: 1, sentence: 'On most maps, north is at the ___.', answer: 'top', wrong: ['bottom', 'left', 'right'] },
  { id: 'geo-1-022', band: 1, sentence: 'On most maps, blue shows ___.', answer: 'water', wrong: ['forests', 'deserts', 'roads'] },
  { id: 'geo-1-023', band: 1, sentence: "The list that explains a map's symbols is the ___.", answer: 'key', wrong: ['scale', 'title', 'border'] },
  { id: 'geo-1-024', band: 1, sentence: "A map's ___ shows how far apart places really are.", answer: 'scale', wrong: ['key', 'title', 'border'] },
  { id: 'geo-1-025', band: 1, sentence: 'A compass rose on a map shows ___.', answer: 'directions', wrong: ['distances', 'heights', 'weather'] },
  { id: 'geo-1-026', band: 1, sentence: 'The opposite of north is ___.', answer: 'south', wrong: ['east', 'west', 'northeast'] },
  { id: 'geo-1-027', band: 1, sentence: 'East is the opposite of ___.', answer: 'west', wrong: ['north', 'south', 'southeast'] },
  { id: 'geo-1-028', band: 1, sentence: 'Halfway between north and east is ___.', answer: 'northeast', wrong: ['northwest', 'southeast', 'southwest'] },
  { id: 'geo-1-029', band: 1, sentence: 'The Sun sets in the ___.', answer: 'west', wrong: ['east', 'north', 'south'] },
  { id: 'geo-1-030', band: 1, sentence: 'The Arctic is the area around the ___ Pole.', answer: 'North', wrong: ['South', 'East', 'West'] },
  { id: 'geo-1-031', band: 1, sentence: 'Polar bears live in the ___.', answer: 'Arctic', wrong: ['Antarctic', 'Sahara', 'Amazon'] },
  { id: 'geo-1-032', band: 1, sentence: 'Land beside the sea is called the ___.', answer: 'coast', wrong: ['peak', 'valley', 'plain'] },
  { id: 'geo-1-033', band: 1, sentence: 'The top of a mountain is called its ___.', answer: 'peak', wrong: ['base', 'valley', 'coast'] },
  { id: 'geo-1-034', band: 1, sentence: 'Low land between mountains is called a ___.', answer: 'valley', wrong: ['peak', 'cliff', 'desert'] },
  { id: 'geo-1-035', band: 1, sentence: 'A mountain that can erupt is a ___.', answer: 'volcano', wrong: ['valley', 'glacier', 'canyon'] },
  { id: 'geo-1-036', band: 1, sentence: 'A river flows from high ground to ___ ground.', answer: 'lower', wrong: ['higher', 'drier', 'colder'] },
  { id: 'geo-1-037', band: 1, sentence: 'The line separating 2 countries is a ___.', answer: 'border', wrong: ['coast', 'horizon', 'harbor'] },
  { id: 'geo-1-038', band: 1, sentence: 'Mountains are ___ than hills.', answer: 'higher', wrong: ['lower', 'flatter', 'wetter'] },
  { id: 'geo-1-039', band: 1, sentence: 'Ships load and unload at a ___.', answer: 'port', wrong: ['peak', 'plain', 'desert'] },
  { id: 'geo-1-040', band: 1, sentence: 'A forest is land covered mostly with ___.', answer: 'trees', wrong: ['sand', 'ice', 'rocks'] },

  // Band 2: famous capitals, famous landmarks, which continent a country is in, well-known country facts
  { id: 'geo-2-001', band: 2, sentence: 'The Eiffel Tower is in ___.', answer: 'Paris', wrong: ['Rome', 'London', 'Madrid'] },
  { id: 'geo-2-002', band: 2, sentence: 'The capital of France is ___.', answer: 'Paris', wrong: ['Lyon', 'Marseille', 'Nice'] },
  { id: 'geo-2-003', band: 2, sentence: 'The capital of Japan is ___.', answer: 'Tokyo', wrong: ['Osaka', 'Kyoto', 'Yokohama'] },
  { id: 'geo-2-004', band: 2, sentence: 'The capital of Italy is ___.', answer: 'Rome', wrong: ['Milan', 'Venice', 'Naples'] },
  { id: 'geo-2-005', band: 2, sentence: 'The capital of Spain is ___.', answer: 'Madrid', wrong: ['Barcelona', 'Seville', 'Valencia'] },
  { id: 'geo-2-006', band: 2, sentence: 'The capital of Germany is ___.', answer: 'Berlin', wrong: ['Munich', 'Hamburg', 'Frankfurt'] },
  { id: 'geo-2-007', band: 2, sentence: 'The capital of the United Kingdom is ___.', answer: 'London', wrong: ['Manchester', 'Liverpool', 'Birmingham'] },
  { id: 'geo-2-008', band: 2, sentence: 'The capital of China is ___.', answer: 'Beijing', wrong: ['Shanghai', 'Guangzhou', 'Shenzhen'] },
  { id: 'geo-2-009', band: 2, sentence: 'The capital of Russia is ___.', answer: 'Moscow', wrong: ['Saint Petersburg', 'Kazan', 'Sochi'] },
  { id: 'geo-2-010', band: 2, sentence: 'The capital of the United States is ___.', answer: 'Washington, D.C.', wrong: ['New York', 'Los Angeles', 'Chicago'] },
  { id: 'geo-2-011', band: 2, sentence: 'The capital of India is ___.', answer: 'New Delhi', wrong: ['Mumbai', 'Kolkata', 'Chennai'] },
  { id: 'geo-2-012', band: 2, sentence: 'The capital of Greece is ___.', answer: 'Athens', wrong: ['Thessaloniki', 'Sparta', 'Corinth'] },
  { id: 'geo-2-013', band: 2, sentence: 'The capital of Mexico is ___.', answer: 'Mexico City', wrong: ['Guadalajara', 'Tijuana', 'Acapulco'] },
  { id: 'geo-2-014', band: 2, sentence: 'The capital of Ireland is ___.', answer: 'Dublin', wrong: ['Cork', 'Galway', 'Limerick'] },
  { id: 'geo-2-015', band: 2, sentence: 'Bangkok is the capital of ___.', answer: 'Thailand', wrong: ['Vietnam', 'Cambodia', 'Laos'] },
  { id: 'geo-2-016', band: 2, sentence: 'The Great Wall is in ___.', answer: 'China', wrong: ['Japan', 'India', 'Vietnam'] },
  { id: 'geo-2-017', band: 2, sentence: 'The Taj Mahal is in ___.', answer: 'India', wrong: ['Pakistan', 'Nepal', 'Sri Lanka'] },
  { id: 'geo-2-018', band: 2, sentence: 'The pyramids of Giza are in ___.', answer: 'Egypt', wrong: ['Mexico', 'Peru', 'Sudan'] },
  { id: 'geo-2-019', band: 2, sentence: 'The Colosseum is in ___.', answer: 'Rome', wrong: ['Athens', 'Paris', 'Madrid'] },
  { id: 'geo-2-020', band: 2, sentence: 'Big Ben is a famous clock tower in ___.', answer: 'London', wrong: ['Paris', 'Dublin', 'Berlin'] },
  { id: 'geo-2-021', band: 2, sentence: 'The Statue of Liberty stands in ___.', answer: 'New York', wrong: ['London', 'Sydney', 'Toronto'] },
  { id: 'geo-2-022', band: 2, sentence: 'Machu Picchu is an old mountain city in ___.', answer: 'Peru', wrong: ['Mexico', 'Chile', 'Brazil'] },
  { id: 'geo-2-023', band: 2, sentence: 'The Leaning Tower of ___ is in Italy.', answer: 'Pisa', wrong: ['Rome', 'Milan', 'Venice'] },
  { id: 'geo-2-024', band: 2, sentence: 'Mount Fuji is in ___.', answer: 'Japan', wrong: ['China', 'South Korea', 'Vietnam'] },
  { id: 'geo-2-025', band: 2, sentence: 'Stonehenge is a ring of ancient stones in ___.', answer: 'England', wrong: ['Ireland', 'France', 'Norway'] },
  { id: 'geo-2-026', band: 2, sentence: 'The Parthenon is an ancient temple in ___.', answer: 'Athens', wrong: ['Rome', 'Cairo', 'Istanbul'] },
  { id: 'geo-2-027', band: 2, sentence: 'Venice is famous for its ___.', answer: 'canals', wrong: ['pyramids', 'volcanoes', 'deserts'] },
  { id: 'geo-2-028', band: 2, sentence: 'The Christ the Redeemer statue is in ___.', answer: 'Brazil', wrong: ['Argentina', 'Portugal', 'Mexico'] },
  { id: 'geo-2-029', band: 2, sentence: 'Brazil is in ___.', answer: 'South America', wrong: ['Africa', 'Asia', 'Europe'] },
  { id: 'geo-2-030', band: 2, sentence: 'Kenya is in ___.', answer: 'Africa', wrong: ['Asia', 'South America', 'Europe'] },
  { id: 'geo-2-031', band: 2, sentence: 'India is in ___.', answer: 'Asia', wrong: ['Africa', 'Europe', 'Australia'] },
  { id: 'geo-2-032', band: 2, sentence: 'Germany is in ___.', answer: 'Europe', wrong: ['Asia', 'Africa', 'North America'] },
  { id: 'geo-2-033', band: 2, sentence: 'Canada is in ___.', answer: 'North America', wrong: ['South America', 'Europe', 'Asia'] },
  { id: 'geo-2-034', band: 2, sentence: 'Mexico is in ___.', answer: 'North America', wrong: ['South America', 'Europe', 'Africa'] },
  { id: 'geo-2-035', band: 2, sentence: 'On a map, Italy looks like a ___.', answer: 'boot', wrong: ['hat', 'star', 'fish'] },
  { id: 'geo-2-036', band: 2, sentence: 'The largest country by area is ___.', answer: 'Russia', wrong: ['Canada', 'China', 'Brazil'] },
  { id: 'geo-2-037', band: 2, sentence: "Canada's flag shows a red ___ leaf.", answer: 'maple', wrong: ['oak', 'palm', 'fig'] },
  { id: 'geo-2-038', band: 2, sentence: 'The Outback is a dry region of ___.', answer: 'Australia', wrong: ['Brazil', 'India', 'Canada'] },
  { id: 'geo-2-039', band: 2, sentence: 'The Amazon rainforest is mostly in ___.', answer: 'Brazil', wrong: ['Peru', 'Mexico', 'Argentina'] },
  { id: 'geo-2-040', band: 2, sentence: 'Spain shares a border with France and ___.', answer: 'Portugal', wrong: ['Italy', 'Germany', 'Greece'] },

  // Band 3: mountains and ranges, rivers, deserts, landform words, volcanoes, reefs, canals and channels
  { id: 'geo-3-001', band: 3, sentence: 'The Andes run along the west of ___.', answer: 'South America', wrong: ['Africa', 'Asia', 'Europe'] },
  { id: 'geo-3-002', band: 3, sentence: 'Mount Everest is in the ___.', answer: 'Himalayas', wrong: ['Andes', 'Alps', 'Rockies'] },
  { id: 'geo-3-003', band: 3, sentence: 'The highest mountain above sea level is Mount ___.', answer: 'Everest', wrong: ['Fuji', 'Kilimanjaro', 'Etna'] },
  { id: 'geo-3-004', band: 3, sentence: 'Kilimanjaro is the highest mountain in ___.', answer: 'Africa', wrong: ['Asia', 'Europe', 'South America'] },
  { id: 'geo-3-005', band: 3, sentence: 'The Alps are a mountain range in ___.', answer: 'Europe', wrong: ['Asia', 'Africa', 'South America'] },
  { id: 'geo-3-006', band: 3, sentence: 'The Rocky Mountains are in ___.', answer: 'North America', wrong: ['South America', 'Europe', 'Asia'] },
  { id: 'geo-3-007', band: 3, sentence: 'Mont Blanc is the highest peak in the ___.', answer: 'Alps', wrong: ['Andes', 'Himalayas', 'Rockies'] },
  { id: 'geo-3-008', band: 3, sentence: 'The Pyrenees lie between France and ___.', answer: 'Spain', wrong: ['Italy', 'Germany', 'Belgium'] },
  { id: 'geo-3-009', band: 3, sentence: 'Mountains in a long line form a mountain ___.', answer: 'range', wrong: ['delta', 'strait', 'plain'] },
  { id: 'geo-3-010', band: 3, sentence: 'The Nile flows north into the ___ Sea.', answer: 'Mediterranean', wrong: ['Red', 'Black', 'Arabian'] },
  { id: 'geo-3-011', band: 3, sentence: 'The Nile flows through the country of ___.', answer: 'Egypt', wrong: ['Morocco', 'Nigeria', 'South Africa'] },
  { id: 'geo-3-012', band: 3, sentence: 'The Amazon River flows into the ___ Ocean.', answer: 'Atlantic', wrong: ['Pacific', 'Indian', 'Arctic'] },
  { id: 'geo-3-013', band: 3, sentence: 'The Danube flows into the ___ Sea.', answer: 'Black', wrong: ['Red', 'North', 'Baltic'] },
  { id: 'geo-3-014', band: 3, sentence: 'The river that flows through London is the ___.', answer: 'Thames', wrong: ['Seine', 'Danube', 'Volga'] },
  { id: 'geo-3-015', band: 3, sentence: 'The river that flows through Paris is the ___.', answer: 'Seine', wrong: ['Thames', 'Rhine', 'Danube'] },
  { id: 'geo-3-016', band: 3, sentence: 'The Ganges River flows through ___.', answer: 'India', wrong: ['China', 'Thailand', 'Iran'] },
  { id: 'geo-3-017', band: 3, sentence: 'The Yangtze is the longest river in ___.', answer: 'China', wrong: ['India', 'Japan', 'Russia'] },
  { id: 'geo-3-018', band: 3, sentence: 'The Grand Canyon was carved by the ___ River.', answer: 'Colorado', wrong: ['Mississippi', 'Missouri', 'Columbia'] },
  { id: 'geo-3-019', band: 3, sentence: 'Victoria Falls is on the ___ River.', answer: 'Zambezi', wrong: ['Nile', 'Congo', 'Niger'] },
  { id: 'geo-3-020', band: 3, sentence: 'The largest hot desert in the world is the ___.', answer: 'Sahara', wrong: ['Gobi', 'Kalahari', 'Mojave'] },
  { id: 'geo-3-021', band: 3, sentence: 'The Gobi Desert is in ___.', answer: 'Asia', wrong: ['Africa', 'Australia', 'South America'] },
  { id: 'geo-3-022', band: 3, sentence: 'The Kalahari Desert is in ___.', answer: 'Africa', wrong: ['Asia', 'Australia', 'North America'] },
  { id: 'geo-3-023', band: 3, sentence: 'The Atacama Desert is in ___.', answer: 'South America', wrong: ['Africa', 'Asia', 'Australia'] },
  { id: 'geo-3-024', band: 3, sentence: 'Land with water on 3 sides is called a ___.', answer: 'peninsula', wrong: ['plateau', 'canyon', 'delta'] },
  { id: 'geo-3-025', band: 3, sentence: 'Land built up by a river at its mouth is a ___.', answer: 'delta', wrong: ['canyon', 'plateau', 'strait'] },
  { id: 'geo-3-026', band: 3, sentence: 'A deep valley with steep rock sides is a ___.', answer: 'canyon', wrong: ['delta', 'plain', 'peninsula'] },
  { id: 'geo-3-027', band: 3, sentence: 'A narrow strip of water joining 2 seas is a ___.', answer: 'strait', wrong: ['delta', 'canyon', 'plateau'] },
  { id: 'geo-3-028', band: 3, sentence: 'A narrow strip of land joining 2 larger lands is an ___.', answer: 'isthmus', wrong: ['island', 'inlet', 'estuary'] },
  { id: 'geo-3-029', band: 3, sentence: 'A group of islands is called an ___.', answer: 'archipelago', wrong: ['isthmus', 'estuary', 'oasis'] },
  { id: 'geo-3-030', band: 3, sentence: 'A flat area of high land is a ___.', answer: 'plateau', wrong: ['canyon', 'delta', 'valley'] },
  { id: 'geo-3-031', band: 3, sentence: 'A large, slow-moving mass of ice is a ___.', answer: 'glacier', wrong: ['geyser', 'delta', 'canyon'] },
  { id: 'geo-3-032', band: 3, sentence: 'A green place with water in a desert is an ___.', answer: 'oasis', wrong: ['isthmus', 'island', 'estuary'] },
  { id: 'geo-3-033', band: 3, sentence: 'A stream that flows into a bigger river is a ___.', answer: 'tributary', wrong: ['delta', 'strait', 'canal'] },
  { id: 'geo-3-034', band: 3, sentence: 'The start of a river is called its ___.', answer: 'source', wrong: ['mouth', 'delta', 'bank'] },
  { id: 'geo-3-035', band: 3, sentence: 'The place where a river meets the sea is its ___.', answer: 'mouth', wrong: ['source', 'bank', 'bed'] },
  { id: 'geo-3-036', band: 3, sentence: 'Mount Etna is a volcano in ___.', answer: 'Italy', wrong: ['Greece', 'Spain', 'Japan'] },
  { id: 'geo-3-037', band: 3, sentence: 'Many volcanoes lie around the Pacific Ring of ___.', answer: 'Fire', wrong: ['Ice', 'Ash', 'Smoke'] },
  { id: 'geo-3-038', band: 3, sentence: 'The Great Barrier Reef lies off the coast of ___.', answer: 'Australia', wrong: ['Brazil', 'India', 'Mexico'] },
  { id: 'geo-3-039', band: 3, sentence: 'The Panama Canal links the Atlantic and ___ oceans.', answer: 'Pacific', wrong: ['Indian', 'Arctic', 'Southern'] },
  { id: 'geo-3-040', band: 3, sentence: 'The English Channel separates England and ___.', answer: 'France', wrong: ['Spain', 'Norway', 'Ireland'] },

  // Band 4: harder capitals (the famous city is often the trap), latitude and longitude, hemispheres, the tropics, time
  { id: 'geo-4-001', band: 4, sentence: 'The capital of Australia is ___.', answer: 'Canberra', wrong: ['Sydney', 'Melbourne', 'Perth'] },
  { id: 'geo-4-002', band: 4, sentence: 'The capital of Canada is ___.', answer: 'Ottawa', wrong: ['Toronto', 'Montreal', 'Vancouver'] },
  { id: 'geo-4-003', band: 4, sentence: 'The capital of Brazil is ___.', answer: 'Brasília', wrong: ['Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { id: 'geo-4-004', band: 4, sentence: 'The capital of New Zealand is ___.', answer: 'Wellington', wrong: ['Auckland', 'Christchurch', 'Queenstown'] },
  { id: 'geo-4-005', band: 4, sentence: 'The capital of Nigeria is ___.', answer: 'Abuja', wrong: ['Lagos', 'Kano', 'Ibadan'] },
  { id: 'geo-4-006', band: 4, sentence: 'The capital of Pakistan is ___.', answer: 'Islamabad', wrong: ['Karachi', 'Lahore', 'Peshawar'] },
  { id: 'geo-4-007', band: 4, sentence: 'The capital of Morocco is ___.', answer: 'Rabat', wrong: ['Casablanca', 'Tangier', 'Agadir'] },
  { id: 'geo-4-008', band: 4, sentence: 'The capital of Portugal is ___.', answer: 'Lisbon', wrong: ['Porto', 'Faro', 'Braga'] },
  { id: 'geo-4-009', band: 4, sentence: 'The capital of Argentina is ___.', answer: 'Buenos Aires', wrong: ['Rosario', 'Mendoza', 'Salta'] },
  { id: 'geo-4-010', band: 4, sentence: 'The capital of Peru is ___.', answer: 'Lima', wrong: ['Arequipa', 'Trujillo', 'Iquitos'] },
  { id: 'geo-4-011', band: 4, sentence: 'The capital of Norway is ___.', answer: 'Oslo', wrong: ['Bergen', 'Trondheim', 'Stavanger'] },
  { id: 'geo-4-012', band: 4, sentence: 'The capital of Sweden is ___.', answer: 'Stockholm', wrong: ['Gothenburg', 'Malmö', 'Uppsala'] },
  { id: 'geo-4-013', band: 4, sentence: 'The capital of Kenya is ___.', answer: 'Nairobi', wrong: ['Mombasa', 'Kisumu', 'Nakuru'] },
  { id: 'geo-4-014', band: 4, sentence: 'The capital of the Philippines is ___.', answer: 'Manila', wrong: ['Cebu City', 'Davao City', 'Zamboanga City'] },
  { id: 'geo-4-015', band: 4, sentence: 'The capital of Colombia is ___.', answer: 'Bogotá', wrong: ['Medellín', 'Cali', 'Cartagena'] },
  { id: 'geo-4-016', band: 4, sentence: 'The capital of Denmark is ___.', answer: 'Copenhagen', wrong: ['Aarhus', 'Odense', 'Aalborg'] },
  { id: 'geo-4-017', band: 4, sentence: 'The capital of the United Arab Emirates is ___.', answer: 'Abu Dhabi', wrong: ['Dubai', 'Sharjah', 'Ajman'] },
  { id: 'geo-4-018', band: 4, sentence: 'The capital of Ecuador is ___.', answer: 'Quito', wrong: ['Guayaquil', 'Cuenca', 'Manta'] },
  { id: 'geo-4-019', band: 4, sentence: 'The capital of Austria is ___.', answer: 'Vienna', wrong: ['Salzburg', 'Innsbruck', 'Graz'] },
  { id: 'geo-4-020', band: 4, sentence: 'The capital of Belgium is ___.', answer: 'Brussels', wrong: ['Antwerp', 'Bruges', 'Ghent'] },
  { id: 'geo-4-021', band: 4, sentence: 'The equator is at ___ degrees latitude.', answer: '0', wrong: ['45', '90', '180'] },
  { id: 'geo-4-022', band: 4, sentence: 'The North Pole is at ___ degrees north latitude.', answer: '90', wrong: ['0', '45', '180'] },
  { id: 'geo-4-023', band: 4, sentence: 'Lines of ___ measure how far north or south a place is.', answer: 'latitude', wrong: ['longitude', 'altitude', 'magnitude'] },
  { id: 'geo-4-024', band: 4, sentence: 'Lines of ___ measure how far east or west a place is.', answer: 'longitude', wrong: ['latitude', 'altitude', 'magnitude'] },
  { id: 'geo-4-025', band: 4, sentence: 'Lines of latitude are also called ___.', answer: 'parallels', wrong: ['meridians', 'poles', 'zones'] },
  { id: 'geo-4-026', band: 4, sentence: 'Lines of longitude are also called ___.', answer: 'meridians', wrong: ['parallels', 'tropics', 'circles'] },
  { id: 'geo-4-027', band: 4, sentence: 'All lines of longitude meet at the ___.', answer: 'poles', wrong: ['equator', 'tropics', 'Prime Meridian'] },
  { id: 'geo-4-028', band: 4, sentence: 'The longest line of latitude is the ___.', answer: 'equator', wrong: ['Arctic Circle', 'Tropic of Cancer', 'Prime Meridian'] },
  { id: 'geo-4-029', band: 4, sentence: 'The equator divides Earth into 2 ___.', answer: 'hemispheres', wrong: ['continents', 'oceans', 'time zones'] },
  { id: 'geo-4-030', band: 4, sentence: 'Europe is entirely in the ___ Hemisphere.', answer: 'Northern', wrong: ['Southern', 'Western', 'Eastern'] },
  { id: 'geo-4-031', band: 4, sentence: 'Antarctica is entirely in the ___ Hemisphere.', answer: 'Southern', wrong: ['Northern', 'Eastern', 'Western'] },
  { id: 'geo-4-032', band: 4, sentence: 'The Tropic of Cancer is ___ of the equator.', answer: 'north', wrong: ['south', 'east', 'west'] },
  { id: 'geo-4-033', band: 4, sentence: 'The Tropic of Capricorn is ___ of the equator.', answer: 'south', wrong: ['north', 'east', 'west'] },
  { id: 'geo-4-034', band: 4, sentence: 'The equator passes through the country of ___.', answer: 'Kenya', wrong: ['Egypt', 'Morocco', 'South Africa'] },
  { id: 'geo-4-035', band: 4, sentence: 'The Tropic of Cancer passes through ___.', answer: 'Mexico', wrong: ['Brazil', 'Canada', 'France'] },
  { id: 'geo-4-036', band: 4, sentence: 'It is summer in Australia in ___.', answer: 'January', wrong: ['June', 'July', 'August'] },
  { id: 'geo-4-037', band: 4, sentence: 'Earth turns about ___ degrees each hour.', answer: '15', wrong: ['24', '60', '90'] },
  { id: 'geo-4-038', band: 4, sentence: 'When it is noon in London, it is ___ in New York.', answer: 'morning', wrong: ['afternoon', 'evening', 'midnight'] },
  { id: 'geo-4-039', band: 4, sentence: 'Days and nights are nearly equal all year near the ___.', answer: 'equator', wrong: ['North Pole', 'South Pole', 'Arctic Circle'] },
  { id: 'geo-4-040', band: 4, sentence: 'The Prime Meridian is at ___ degrees longitude.', answer: '0', wrong: ['90', '180', '360'] },

  // Band 5: the Prime Meridian and the Date Line, landlocked and enclosed countries, records that don't change, tricky locations
  { id: 'geo-5-001', band: 5, sentence: 'The largest island in the world is ___.', answer: 'Greenland', wrong: ['Borneo', 'Madagascar', 'Iceland'] },
  { id: 'geo-5-002', band: 5, sentence: 'The Prime Meridian passes through ___ in London.', answer: 'Greenwich', wrong: ['Westminster', 'Wimbledon', 'Chelsea'] },
  { id: 'geo-5-003', band: 5, sentence: 'The International Date Line is mostly in the ___ Ocean.', answer: 'Pacific', wrong: ['Atlantic', 'Indian', 'Arctic'] },
  { id: 'geo-5-004', band: 5, sentence: 'The International Date Line is near ___ degrees longitude.', answer: '180', wrong: ['0', '90', '360'] },
  { id: 'geo-5-005', band: 5, sentence: 'Going west across the Date Line, the date moves ___.', answer: '1 day ahead', wrong: ['1 day back', '1 hour ahead', '1 hour back'] },
  { id: 'geo-5-006', band: 5, sentence: 'A country with no coastline is called ___.', answer: 'landlocked', wrong: ['coastal', 'tropical', 'peninsular'] },
  { id: 'geo-5-007', band: 5, sentence: '___ is a landlocked country in South America.', answer: 'Paraguay', wrong: ['Peru', 'Chile', 'Uruguay'] },
  { id: 'geo-5-008', band: 5, sentence: '___ is a landlocked country in Africa.', answer: 'Chad', wrong: ['Egypt', 'Kenya', 'Ghana'] },
  { id: 'geo-5-009', band: 5, sentence: '___ is a landlocked country in Europe.', answer: 'Switzerland', wrong: ['Italy', 'Spain', 'Norway'] },
  { id: 'geo-5-010', band: 5, sentence: '___ is a landlocked country in Asia.', answer: 'Mongolia', wrong: ['Japan', 'Vietnam', 'India'] },
  { id: 'geo-5-011', band: 5, sentence: 'The smallest country in the world is ___.', answer: 'Vatican City', wrong: ['Monaco', 'San Marino', 'Malta'] },
  { id: 'geo-5-012', band: 5, sentence: 'San Marino is completely surrounded by ___.', answer: 'Italy', wrong: ['France', 'Spain', 'Austria'] },
  { id: 'geo-5-013', band: 5, sentence: 'Lesotho is completely surrounded by ___.', answer: 'South Africa', wrong: ['Kenya', 'Nigeria', 'Egypt'] },
  { id: 'geo-5-014', band: 5, sentence: 'The deepest lake in the world is Lake ___.', answer: 'Baikal', wrong: ['Victoria', 'Superior', 'Titicaca'] },
  { id: 'geo-5-015', band: 5, sentence: 'The largest lake in Africa is Lake ___.', answer: 'Victoria', wrong: ['Chad', 'Tanganyika', 'Turkana'] },
  { id: 'geo-5-016', band: 5, sentence: 'The deepest part of the ocean is in the ___ Trench.', answer: 'Mariana', wrong: ['Tonga', 'Java', 'Puerto Rico'] },
  { id: 'geo-5-017', band: 5, sentence: 'Counting cold deserts, the largest desert is in ___.', answer: 'Antarctica', wrong: ['Africa', 'Asia', 'Australia'] },
  { id: 'geo-5-018', band: 5, sentence: 'The longest mountain range on land is the ___.', answer: 'Andes', wrong: ['Himalayas', 'Rockies', 'Alps'] },
  { id: 'geo-5-019', band: 5, sentence: 'The city of Istanbul lies in both Europe and ___.', answer: 'Asia', wrong: ['Africa', 'Australia', 'Antarctica'] },
  { id: 'geo-5-020', band: 5, sentence: 'The only continent with no countries is ___.', answer: 'Antarctica', wrong: ['Australia', 'Europe', 'Africa'] },
  { id: 'geo-5-021', band: 5, sentence: 'Both the equator and the Prime Meridian cross ___.', answer: 'Africa', wrong: ['Asia', 'Europe', 'Australia'] },
  { id: 'geo-5-022', band: 5, sentence: 'The Suez Canal links the Mediterranean and the ___ Sea.', answer: 'Red', wrong: ['Black', 'Arabian', 'Baltic'] },
  { id: 'geo-5-023', band: 5, sentence: 'The Strait of Gibraltar separates Spain and ___.', answer: 'Morocco', wrong: ['Algeria', 'Tunisia', 'Portugal'] },
  { id: 'geo-5-024', band: 5, sentence: 'The Bering Strait separates Asia and ___.', answer: 'North America', wrong: ['Europe', 'Australia', 'Africa'] },
  { id: 'geo-5-025', band: 5, sentence: 'Mount Kilimanjaro is in ___.', answer: 'Tanzania', wrong: ['Kenya', 'Uganda', 'Ethiopia'] },
  { id: 'geo-5-026', band: 5, sentence: 'Madagascar lies in the ___ Ocean.', answer: 'Indian', wrong: ['Atlantic', 'Pacific', 'Arctic'] },
  { id: 'geo-5-027', band: 5, sentence: 'The Galápagos Islands belong to ___.', answer: 'Ecuador', wrong: ['Peru', 'Chile', 'Colombia'] },
  { id: 'geo-5-028', band: 5, sentence: 'The longest river in Europe is the ___.', answer: 'Volga', wrong: ['Danube', 'Rhine', 'Thames'] },
  { id: 'geo-5-029', band: 5, sentence: 'Lake Titicaca lies between Peru and ___.', answer: 'Bolivia', wrong: ['Chile', 'Brazil', 'Ecuador'] },
  { id: 'geo-5-030', band: 5, sentence: 'Cape Horn is near the southern tip of ___.', answer: 'South America', wrong: ['Africa', 'Australia', 'Asia'] },
  { id: 'geo-5-031', band: 5, sentence: 'The south side of Mount Everest is in ___.', answer: 'Nepal', wrong: ['India', 'Bhutan', 'Pakistan'] },
  { id: 'geo-5-032', band: 5, sentence: 'The second-highest mountain on Earth is ___.', answer: 'K2', wrong: ['Mont Blanc', 'Kilimanjaro', 'Mount Fuji'] },
  { id: 'geo-5-033', band: 5, sentence: 'The river that carries the most water is the ___.', answer: 'Amazon', wrong: ['Nile', 'Yangtze', 'Mississippi'] },
  { id: 'geo-5-034', band: 5, sentence: 'Latitude 0, longitude 0 is in the ___ Ocean.', answer: 'Atlantic', wrong: ['Pacific', 'Indian', 'Arctic'] },
  { id: 'geo-5-035', band: 5, sentence: 'At the North Pole, every direction points ___.', answer: 'south', wrong: ['north', 'east', 'west'] },
  { id: 'geo-5-036', band: 5, sentence: 'On June 21, the Sun never sets north of the ___.', answer: 'Arctic Circle', wrong: ['equator', 'Tropic of Cancer', 'Prime Meridian'] },
  { id: 'geo-5-037', band: 5, sentence: 'Ecuador is named after the ___.', answer: 'equator', wrong: ['Andes', 'Amazon', 'Pacific'] },
  { id: 'geo-5-038', band: 5, sentence: 'The country with the longest coastline is ___.', answer: 'Canada', wrong: ['Russia', 'Australia', 'Indonesia'] },
  { id: 'geo-5-039', band: 5, sentence: 'The White Nile and the ___ Nile join to form the Nile.', answer: 'Blue', wrong: ['Red', 'Black', 'Green'] },
  { id: 'geo-5-040', band: 5, sentence: 'People in Brazil mostly speak ___.', answer: 'Portuguese', wrong: ['Spanish', 'French', 'English'] },
];
