import type { BankItem } from './bank';

// Rules for every item (checked mechanically in __tests__/game/bank-content-test.ts, except the
// first five, which need a human): exactly ONE choice is true in that exact sentence, and the wrong
// choices are clearly false but from the same category (planets with planets, organs with organs);
// true as written at school level, qualified where needed ("at sea level", "most"); no facts that
// change over time (moon counts, records) and no popular myths; suitable for all ages. Numbers as
// digits, metric units, chemical formulas with subscript digits (H₂O), American spelling. Four
// choices distinct ignoring case, 1-3 words and at most 16 characters, capitalised when the blank
// starts the sentence; sentences at most 60 characters.
// Bands: 1 everyday science, 2 Earth and space, 3 living things and the body, 4 matter, forces and
// energy, 5 tricky science.
export const SCIENCE_BANK: readonly BankItem[] = [
  // Band 1: animal bodies and babies, the senses, plants, the Sun and weather, ice and water
  { id: 'sci-1-001', band: 1, sentence: 'A spider has ___ legs.', answer: '8', wrong: ['6', '4', '10'] },
  { id: 'sci-1-002', band: 1, sentence: 'An adult insect has ___ legs.', answer: '6', wrong: ['8', '4', '10'] },
  { id: 'sci-1-003', band: 1, sentence: 'Birds are covered in ___.', answer: 'feathers', wrong: ['fur', 'wool', 'shells'] },
  { id: 'sci-1-004', band: 1, sentence: 'Fish breathe underwater using their ___.', answer: 'gills', wrong: ['lungs', 'noses', 'fins'] },
  { id: 'sci-1-005', band: 1, sentence: 'Fish use their ___ and tail to swim.', answer: 'fins', wrong: ['wings', 'legs', 'arms'] },
  { id: 'sci-1-006', band: 1, sentence: 'A baby dog is called a ___.', answer: 'puppy', wrong: ['kitten', 'calf', 'foal'] },
  { id: 'sci-1-007', band: 1, sentence: 'A baby cat is called a ___.', answer: 'kitten', wrong: ['puppy', 'chick', 'lamb'] },
  { id: 'sci-1-008', band: 1, sentence: 'A baby sheep is called a ___.', answer: 'lamb', wrong: ['calf', 'foal', 'puppy'] },
  { id: 'sci-1-009', band: 1, sentence: 'A baby horse is called a ___.', answer: 'foal', wrong: ['calf', 'lamb', 'kitten'] },
  { id: 'sci-1-010', band: 1, sentence: 'We see with our ___.', answer: 'eyes', wrong: ['ears', 'nose', 'tongue'] },
  { id: 'sci-1-011', band: 1, sentence: 'We hear sounds with our ___.', answer: 'ears', wrong: ['eyes', 'nose', 'skin'] },
  { id: 'sci-1-012', band: 1, sentence: 'We smell with our ___.', answer: 'nose', wrong: ['ears', 'eyes', 'hands'] },
  { id: 'sci-1-013', band: 1, sentence: 'We taste food with our ___.', answer: 'tongue', wrong: ['ears', 'eyes', 'hair'] },
  { id: 'sci-1-014', band: 1, sentence: 'Plants need ___ to make their own food.', answer: 'light', wrong: ['darkness', 'sand', 'salt'] },
  { id: 'sci-1-015', band: 1, sentence: 'A plant takes in water through its ___.', answer: 'roots', wrong: ['flowers', 'petals', 'fruit'] },
  { id: 'sci-1-016', band: 1, sentence: 'An oak tree grows from an ___.', answer: 'acorn', wrong: ['egg', 'apple', 'onion'] },
  { id: 'sci-1-017', band: 1, sentence: 'Honeybees make ___ from nectar.', answer: 'honey', wrong: ['milk', 'jam', 'silk'] },
  { id: 'sci-1-018', band: 1, sentence: 'Honeybees live together in a ___.', answer: 'hive', wrong: ['den', 'web', 'stable'] },
  { id: 'sci-1-019', band: 1, sentence: 'The Sun rises in the ___.', answer: 'east', wrong: ['west', 'north', 'south'] },
  { id: 'sci-1-020', band: 1, sentence: 'The Sun is a ___.', answer: 'star', wrong: ['planet', 'moon', 'comet'] },
  { id: 'sci-1-021', band: 1, sentence: "Most of Earth's light and heat comes from the ___.", answer: 'Sun', wrong: ['Moon', 'clouds', 'volcanoes'] },
  { id: 'sci-1-022', band: 1, sentence: 'Rain falls from ___.', answer: 'clouds', wrong: ['stars', 'mountains', 'rainbows'] },
  { id: 'sci-1-023', band: 1, sentence: 'Sunlight shining through ___ can make a rainbow.', answer: 'raindrops', wrong: ['bricks', 'wood', 'soil'] },
  { id: 'sci-1-024', band: 1, sentence: 'When water freezes, it turns into ___.', answer: 'ice', wrong: ['steam', 'sand', 'glass'] },
  { id: 'sci-1-025', band: 1, sentence: 'When ice melts, it turns into ___.', answer: 'water', wrong: ['steam', 'snow', 'salt'] },
  { id: 'sci-1-026', band: 1, sentence: 'Snow is made of tiny ___ crystals.', answer: 'ice', wrong: ['salt', 'sugar', 'sand'] },
  { id: 'sci-1-027', band: 1, sentence: 'Wind is ___ that is moving.', answer: 'air', wrong: ['water', 'light', 'sound'] },
  { id: 'sci-1-028', band: 1, sentence: 'The loud sound after lightning is called ___.', answer: 'thunder', wrong: ['hail', 'fog', 'frost'] },
  { id: 'sci-1-029', band: 1, sentence: 'A shadow forms when something blocks ___.', answer: 'light', wrong: ['sound', 'air', 'water'] },
  { id: 'sci-1-030', band: 1, sentence: 'Most fish are covered in ___.', answer: 'scales', wrong: ['feathers', 'fur', 'wool'] },
  { id: 'sci-1-031', band: 1, sentence: 'Cows mostly eat ___.', answer: 'grass', wrong: ['meat', 'fish', 'insects'] },
  { id: 'sci-1-032', band: 1, sentence: 'Most birds lay their eggs in a ___.', answer: 'nest', wrong: ['hive', 'web', 'den'] },
  { id: 'sci-1-033', band: 1, sentence: 'Many spiders catch insects in a ___.', answer: 'web', wrong: ['hive', 'shell', 'nest'] },
  { id: 'sci-1-034', band: 1, sentence: 'A caterpillar can grow up to become a ___.', answer: 'butterfly', wrong: ['bee', 'spider', 'beetle'] },
  { id: 'sci-1-035', band: 1, sentence: 'Most turtles have a hard ___ on their backs.', answer: 'shell', wrong: ['wing', 'mane', 'horn'] },
  { id: 'sci-1-036', band: 1, sentence: 'An elephant picks up food with its ___.', answer: 'trunk', wrong: ['tail', 'ears', 'feet'] },
  { id: 'sci-1-037', band: 1, sentence: 'A mother kangaroo carries her baby in a ___.', answer: 'pouch', wrong: ['nest', 'shell', 'hive'] },
  { id: 'sci-1-038', band: 1, sentence: 'Penguins are birds that cannot ___.', answer: 'fly', wrong: ['swim', 'walk', 'eat'] },
  { id: 'sci-1-039', band: 1, sentence: 'Earthworms live in the ___.', answer: 'soil', wrong: ['sky', 'treetops', 'ocean'] },
  { id: 'sci-1-040', band: 1, sentence: 'The leaves of many trees change color in ___.', answer: 'autumn', wrong: ['spring', 'summer', 'winter'] },

  // Band 2: the Sun, Moon and planets, day and year, the water cycle, weather tools, rocks, Earth's layers
  { id: 'sci-2-001', band: 2, sentence: 'The planet closest to the Sun is ___.', answer: 'Mercury', wrong: ['Venus', 'Mars', 'Earth'] },
  { id: 'sci-2-002', band: 2, sentence: '___ is the largest planet in our solar system.', answer: 'Jupiter', wrong: ['Saturn', 'Neptune', 'Earth'] },
  { id: 'sci-2-003', band: 2, sentence: 'Mars is often called the ___ Planet.', answer: 'Red', wrong: ['Blue', 'Green', 'Ringed'] },
  { id: 'sci-2-004', band: 2, sentence: 'The planet famous for its bright rings is ___.', answer: 'Saturn', wrong: ['Mars', 'Venus', 'Mercury'] },
  { id: 'sci-2-005', band: 2, sentence: 'Earth is the ___ planet from the Sun.', answer: '3rd', wrong: ['1st', '2nd', '4th'] },
  { id: 'sci-2-006', band: 2, sentence: 'Earth takes about ___ days to go around the Sun.', answer: '365', wrong: ['30', '100', '500'] },
  { id: 'sci-2-007', band: 2, sentence: 'Earth spins once on its axis about every ___.', answer: '24 hours', wrong: ['1 hour', '7 days', '365 days'] },
  { id: 'sci-2-008', band: 2, sentence: 'We have day and night because Earth ___.', answer: 'spins', wrong: ['orbits the Sun', 'is tilted', 'has a moon'] },
  { id: 'sci-2-009', band: 2, sentence: 'The Moon travels around ___.', answer: 'Earth', wrong: ['Mars', 'Venus', 'Jupiter'] },
  { id: 'sci-2-010', band: 2, sentence: 'The Moon takes about a ___ to orbit Earth.', answer: 'month', wrong: ['day', 'week', 'year'] },
  { id: 'sci-2-011', band: 2, sentence: 'The closest star to Earth is the ___.', answer: 'Sun', wrong: ['Moon', 'North Star', 'Big Dipper'] },
  { id: 'sci-2-012', band: 2, sentence: 'Scientists use a ___ to look at distant stars.', answer: 'telescope', wrong: ['microscope', 'stethoscope', 'periscope'] },
  { id: 'sci-2-013', band: 2, sentence: 'The path a planet takes around the Sun is its ___.', answer: 'orbit', wrong: ['axis', 'atmosphere', 'core'] },
  { id: 'sci-2-014', band: 2, sentence: 'Water turning into vapor is called ___.', answer: 'evaporation', wrong: ['condensation', 'precipitation', 'freezing'] },
  { id: 'sci-2-015', band: 2, sentence: 'Water vapor cooling to form clouds is called ___.', answer: 'condensation', wrong: ['evaporation', 'precipitation', 'melting'] },
  { id: 'sci-2-016', band: 2, sentence: 'Rain, snow, and hail are all types of ___.', answer: 'precipitation', wrong: ['evaporation', 'condensation', 'erosion'] },
  { id: 'sci-2-017', band: 2, sentence: 'A ___ measures temperature.', answer: 'thermometer', wrong: ['barometer', 'ruler', 'compass'] },
  { id: 'sci-2-018', band: 2, sentence: 'A ___ shows which direction is north.', answer: 'compass', wrong: ['thermometer', 'barometer', 'microscope'] },
  { id: 'sci-2-019', band: 2, sentence: 'Melted rock that flows out of a volcano is ___.', answer: 'lava', wrong: ['magma', 'sand', 'ash'] },
  { id: 'sci-2-020', band: 2, sentence: 'Melted rock under the ground is called ___.', answer: 'magma', wrong: ['lava', 'coal', 'clay'] },
  { id: 'sci-2-021', band: 2, sentence: 'Rocks that form from cooled lava or magma are ___ rocks.', answer: 'igneous', wrong: ['sedimentary', 'metamorphic', 'fossil'] },
  { id: 'sci-2-022', band: 2, sentence: 'The remains of ancient life preserved in rock are ___.', answer: 'fossils', wrong: ['meteors', 'pebbles', 'magma'] },
  { id: 'sci-2-023', band: 2, sentence: 'The force that pulls things toward Earth is ___.', answer: 'gravity', wrong: ['friction', 'magnetism', 'wind'] },
  { id: 'sci-2-024', band: 2, sentence: "Most of Earth's surface is covered by ___.", answer: 'water', wrong: ['sand', 'ice', 'forests'] },
  { id: 'sci-2-025', band: 2, sentence: 'The layer of air around Earth is the ___.', answer: 'atmosphere', wrong: ['crust', 'core', 'mantle'] },
  { id: 'sci-2-026', band: 2, sentence: 'The hard outer layer of Earth is the ___.', answer: 'crust', wrong: ['core', 'mantle', 'atmosphere'] },
  { id: 'sci-2-027', band: 2, sentence: 'The center of Earth is called the ___.', answer: 'core', wrong: ['crust', 'mantle', 'equator'] },
  { id: 'sci-2-028', band: 2, sentence: 'The imaginary line around the middle of Earth is the ___.', answer: 'equator', wrong: ['axis', 'North Pole', 'orbit'] },
  { id: 'sci-2-029', band: 2, sentence: "Earth's crust is broken into huge pieces called ___.", answer: 'plates', wrong: ['poles', 'craters', 'cores'] },
  { id: 'sci-2-030', band: 2, sentence: 'A group of stars that forms a pattern is a ___.', answer: 'constellation', wrong: ['comet', 'planet', 'meteor'] },
  { id: 'sci-2-031', band: 2, sentence: 'Our galaxy is called the ___.', answer: 'Milky Way', wrong: ['Andromeda', 'Big Dipper', 'solar system'] },
  { id: 'sci-2-032', band: 2, sentence: 'The Sun is at the center of our ___.', answer: 'solar system', wrong: ['galaxy', 'planet', 'universe'] },
  { id: 'sci-2-033', band: 2, sentence: 'When the Moon blocks the Sun, it is a solar ___.', answer: 'eclipse', wrong: ['flare', 'wind', 'system'] },
  { id: 'sci-2-034', band: 2, sentence: 'Slow-moving rivers of ice on land are called ___.', answer: 'glaciers', wrong: ['icebergs', 'geysers', 'volcanoes'] },
  { id: 'sci-2-035', band: 2, sentence: 'Hot water that shoots out of the ground is a ___.', answer: 'geyser', wrong: ['glacier', 'canyon', 'delta'] },
  { id: 'sci-2-036', band: 2, sentence: 'The Moon has many ___ made by space rocks crashing into it.', answer: 'craters', wrong: ['volcanoes', 'rivers', 'forests'] },
  { id: 'sci-2-037', band: 2, sentence: 'Shooting stars are space rocks burning up in the ___.', answer: 'atmosphere', wrong: ['ocean', 'clouds', 'Moon'] },
  { id: 'sci-2-038', band: 2, sentence: 'A ___ is a huge storm with strong spinning winds.', answer: 'hurricane', wrong: ['drought', 'fog', 'rainbow'] },
  { id: 'sci-2-039', band: 2, sentence: "The Moon's changing shapes in our sky are called ___.", answer: 'phases', wrong: ['orbits', 'craters', 'seasons'] },
  { id: 'sci-2-040', band: 2, sentence: 'Scientists who study the stars and planets are ___.', answer: 'astronomers', wrong: ['astronauts', 'geologists', 'biologists'] },

  // Band 3: organs and the skeleton, photosynthesis, seeds and pollination, food chains, life cycles, animal groups
  { id: 'sci-3-001', band: 3, sentence: 'The ___ pumps blood around your body.', answer: 'heart', wrong: ['brain', 'liver', 'stomach'] },
  { id: 'sci-3-002', band: 3, sentence: 'We breathe in air using our ___.', answer: 'lungs', wrong: ['kidneys', 'liver', 'stomach'] },
  { id: 'sci-3-003', band: 3, sentence: 'Your ___ controls your thoughts and movements.', answer: 'brain', wrong: ['heart', 'stomach', 'liver'] },
  { id: 'sci-3-004', band: 3, sentence: 'Most food is digested in the stomach and the ___.', answer: 'small intestine', wrong: ['lungs', 'heart', 'kidneys'] },
  { id: 'sci-3-005', band: 3, sentence: 'An adult human usually has ___ bones.', answer: '206', wrong: ['106', '306', '26'] },
  { id: 'sci-3-006', band: 3, sentence: 'Your ___ protects your brain.', answer: 'skull', wrong: ['spine', 'kneecap', 'pelvis'] },
  { id: 'sci-3-007', band: 3, sentence: 'Your ___ protect your heart and lungs.', answer: 'ribs', wrong: ['kneecaps', 'hip bones', 'teeth'] },
  { id: 'sci-3-008', band: 3, sentence: 'The human heart has ___ chambers.', answer: '4', wrong: ['2', '3', '6'] },
  { id: 'sci-3-009', band: 3, sentence: 'Your ___ filter waste from your blood.', answer: 'kidneys', wrong: ['bones', 'muscles', 'ears'] },
  { id: 'sci-3-010', band: 3, sentence: 'Muscles are attached to bones by ___.', answer: 'tendons', wrong: ['ligaments', 'nerves', 'veins'] },
  { id: 'sci-3-011', band: 3, sentence: 'Messages travel between your brain and body along ___.', answer: 'nerves', wrong: ['muscles', 'bones', 'tendons'] },
  { id: 'sci-3-012', band: 3, sentence: 'Flat back teeth used for grinding food are ___.', answer: 'molars', wrong: ['incisors', 'canines', 'tusks'] },
  { id: 'sci-3-013', band: 3, sentence: 'Your body gets its energy from ___.', answer: 'food', wrong: ['water', 'vitamins', 'noise'] },
  { id: 'sci-3-014', band: 3, sentence: 'Plants make their food by a process called ___.', answer: 'photosynthesis', wrong: ['digestion', 'respiration', 'evaporation'] },
  { id: 'sci-3-015', band: 3, sentence: 'Plants take in ___ from the air to make food.', answer: 'carbon dioxide', wrong: ['oxygen', 'nitrogen', 'helium'] },
  { id: 'sci-3-016', band: 3, sentence: 'During photosynthesis, plants give off ___.', answer: 'oxygen', wrong: ['carbon dioxide', 'nitrogen', 'smoke'] },
  { id: 'sci-3-017', band: 3, sentence: 'The green substance in leaves that traps sunlight is ___.', answer: 'chlorophyll', wrong: ['chalk', 'nectar', 'pollen'] },
  { id: 'sci-3-018', band: 3, sentence: 'In flowering plants, seeds are made in the ___.', answer: 'flower', wrong: ['root', 'stem', 'leaf'] },
  { id: 'sci-3-019', band: 3, sentence: 'When a seed begins to grow, it is called ___.', answer: 'germination', wrong: ['pollination', 'erosion', 'digestion'] },
  { id: 'sci-3-020', band: 3, sentence: 'Roots take in water and ___ from the soil.', answer: 'nutrients', wrong: ['sunlight', 'pollen', 'nectar'] },
  { id: 'sci-3-021', band: 3, sentence: 'Bees help plants by carrying ___ between flowers.', answer: 'pollen', wrong: ['nectar', 'honey', 'seeds'] },
  { id: 'sci-3-022', band: 3, sentence: 'Moving pollen from flower to flower is called ___.', answer: 'pollination', wrong: ['germination', 'photosynthesis', 'migration'] },
  { id: 'sci-3-023', band: 3, sentence: 'Animals that eat only plants are ___.', answer: 'herbivores', wrong: ['carnivores', 'omnivores', 'predators'] },
  { id: 'sci-3-024', band: 3, sentence: 'Animals that eat only meat are ___.', answer: 'carnivores', wrong: ['herbivores', 'omnivores', 'producers'] },
  { id: 'sci-3-025', band: 3, sentence: 'Animals that eat both plants and meat are ___.', answer: 'omnivores', wrong: ['herbivores', 'carnivores', 'producers'] },
  { id: 'sci-3-026', band: 3, sentence: 'In a food chain, plants are called ___.', answer: 'producers', wrong: ['consumers', 'predators', 'decomposers'] },
  { id: 'sci-3-027', band: 3, sentence: 'Living things that break down dead matter are ___.', answer: 'decomposers', wrong: ['producers', 'predators', 'herbivores'] },
  { id: 'sci-3-028', band: 3, sentence: 'An animal that hunts other animals for food is a ___.', answer: 'predator', wrong: ['prey', 'producer', 'herbivore'] },
  { id: 'sci-3-029', band: 3, sentence: 'A caterpillar changing into a butterfly is called ___.', answer: 'metamorphosis', wrong: ['photosynthesis', 'evaporation', 'hibernation'] },
  { id: 'sci-3-030', band: 3, sentence: 'Most frogs hatch from eggs as ___.', answer: 'tadpoles', wrong: ['caterpillars', 'chicks', 'cubs'] },
  { id: 'sci-3-031', band: 3, sentence: 'Animals that sleep through the winter are said to ___.', answer: 'hibernate', wrong: ['migrate', 'evaporate', 'photosynthesize'] },
  { id: 'sci-3-032', band: 3, sentence: 'The yearly flight of birds to warmer places is called ___.', answer: 'migration', wrong: ['hibernation', 'molting', 'evolution'] },
  { id: 'sci-3-033', band: 3, sentence: 'Animals with a backbone are called ___.', answer: 'vertebrates', wrong: ['invertebrates', 'insects', 'mollusks'] },
  { id: 'sci-3-034', band: 3, sentence: 'Whales are ___, not fish.', answer: 'mammals', wrong: ['reptiles', 'birds', 'amphibians'] },
  { id: 'sci-3-035', band: 3, sentence: 'Bats are the only ___ that can truly fly.', answer: 'mammals', wrong: ['insects', 'birds', 'reptiles'] },
  { id: 'sci-3-036', band: 3, sentence: 'Frogs and salamanders are ___.', answer: 'amphibians', wrong: ['reptiles', 'mammals', 'insects'] },
  { id: 'sci-3-037', band: 3, sentence: 'Snakes and lizards are ___.', answer: 'reptiles', wrong: ['amphibians', 'mammals', 'insects'] },
  { id: 'sci-3-038', band: 3, sentence: 'Spiders are not insects; they are ___.', answer: 'arachnids', wrong: ['reptiles', 'mammals', 'mollusks'] },
  { id: 'sci-3-039', band: 3, sentence: 'Mammals feed their babies ___.', answer: 'milk', wrong: ['nectar', 'seeds', 'pollen'] },
  { id: 'sci-3-040', band: 3, sentence: 'The natural home of an animal is its ___.', answer: 'habitat', wrong: ['orbit', 'skeleton', 'diet'] },

  // Band 4: states of matter, changes, magnets, electricity, light and sound, forces, energy
  { id: 'sci-4-001', band: 4, sentence: 'Solid, liquid, and gas are states of ___.', answer: 'matter', wrong: ['energy', 'light', 'motion'] },
  { id: 'sci-4-002', band: 4, sentence: 'Pure water freezes at ___ °C.', answer: '0', wrong: ['100', '32', '10'] },
  { id: 'sci-4-003', band: 4, sentence: 'At sea level, water boils at ___ °C.', answer: '100', wrong: ['0', '50', '212'] },
  { id: 'sci-4-004', band: 4, sentence: 'A solid turning into a liquid is called ___.', answer: 'melting', wrong: ['freezing', 'boiling', 'condensing'] },
  { id: 'sci-4-005', band: 4, sentence: 'A liquid turning into a solid is called ___.', answer: 'freezing', wrong: ['melting', 'boiling', 'evaporating'] },
  { id: 'sci-4-006', band: 4, sentence: 'A ___ has a fixed shape and a fixed volume.', answer: 'solid', wrong: ['liquid', 'gas', 'plasma'] },
  { id: 'sci-4-007', band: 4, sentence: 'A liquid takes the shape of its ___.', answer: 'container', wrong: ['color', 'weight', 'temperature'] },
  { id: 'sci-4-008', band: 4, sentence: 'Water vapor is water in the form of a ___.', answer: 'gas', wrong: ['solid', 'liquid', 'metal'] },
  { id: 'sci-4-009', band: 4, sentence: 'Iron rusting is an example of a ___ change.', answer: 'chemical', wrong: ['physical', 'magnetic', 'nuclear'] },
  { id: 'sci-4-010', band: 4, sentence: 'Melting ice is an example of a ___ change.', answer: 'physical', wrong: ['chemical', 'magnetic', 'nuclear'] },
  { id: 'sci-4-011', band: 4, sentence: 'Mixing salt into water makes a ___.', answer: 'solution', wrong: ['magnet', 'metal', 'gas'] },
  { id: 'sci-4-012', band: 4, sentence: 'Like magnetic poles ___ each other.', answer: 'repel', wrong: ['attract', 'melt', 'freeze'] },
  { id: 'sci-4-013', band: 4, sentence: 'Opposite magnetic poles ___ each other.', answer: 'attract', wrong: ['repel', 'melt', 'freeze'] },
  { id: 'sci-4-014', band: 4, sentence: "A magnet's poles are called north and ___.", answer: 'south', wrong: ['east', 'west', 'top'] },
  { id: 'sci-4-015', band: 4, sentence: 'Materials that let electricity flow easily are ___.', answer: 'conductors', wrong: ['insulators', 'mirrors', 'fuels'] },
  { id: 'sci-4-016', band: 4, sentence: 'Rubber and plastic are good electrical ___.', answer: 'insulators', wrong: ['conductors', 'magnets', 'batteries'] },
  { id: 'sci-4-017', band: 4, sentence: '___ is a metal often used in electrical wires.', answer: 'Copper', wrong: ['Rubber', 'Glass', 'Wood'] },
  { id: 'sci-4-018', band: 4, sentence: 'A ___ turns a circuit on and off.', answer: 'switch', wrong: ['bulb', 'wire', 'battery'] },
  { id: 'sci-4-019', band: 4, sentence: 'Electricity flows around a complete ___.', answer: 'circuit', wrong: ['magnet', 'prism', 'lever'] },
  { id: 'sci-4-020', band: 4, sentence: 'Light travels in ___ lines.', answer: 'straight', wrong: ['curved', 'zigzag', 'wavy'] },
  { id: 'sci-4-021', band: 4, sentence: 'Bouncing light off a mirror is called ___.', answer: 'reflection', wrong: ['refraction', 'absorption', 'evaporation'] },
  { id: 'sci-4-022', band: 4, sentence: 'Light bending as it enters water is called ___.', answer: 'refraction', wrong: ['reflection', 'absorption', 'vibration'] },
  { id: 'sci-4-023', band: 4, sentence: 'A prism splits white light into a ___ of colors.', answer: 'spectrum', wrong: ['shadow', 'mirror', 'lens'] },
  { id: 'sci-4-024', band: 4, sentence: 'Sound is made when objects ___.', answer: 'vibrate', wrong: ['melt', 'freeze', 'glow'] },
  { id: 'sci-4-025', band: 4, sentence: 'Sound cannot travel through ___.', answer: 'empty space', wrong: ['water', 'air', 'steel'] },
  { id: 'sci-4-026', band: 4, sentence: 'An echo is a sound that ___ off a surface.', answer: 'bounces', wrong: ['melts', 'freezes', 'glows'] },
  { id: 'sci-4-027', band: 4, sentence: 'We see lightning before thunder because light is ___.', answer: 'faster', wrong: ['slower', 'brighter', 'hotter'] },
  { id: 'sci-4-028', band: 4, sentence: 'The force that slows down things rubbing together is ___.', answer: 'friction', wrong: ['gravity', 'magnetism', 'electricity'] },
  { id: 'sci-4-029', band: 4, sentence: 'Air resistance is a force that ___ falling objects.', answer: 'slows down', wrong: ['speeds up', 'pulls down', 'magnetizes'] },
  { id: 'sci-4-030', band: 4, sentence: 'A push or a pull is called a ___.', answer: 'force', wrong: ['mass', 'volume', 'speed'] },
  { id: 'sci-4-031', band: 4, sentence: 'Energy from the Sun is called ___ energy.', answer: 'solar', wrong: ['tidal', 'geothermal', 'electrical'] },
  { id: 'sci-4-032', band: 4, sentence: 'Wind, solar, and water power are ___ energy sources.', answer: 'renewable', wrong: ['nonrenewable', 'fossil', 'chemical'] },
  { id: 'sci-4-033', band: 4, sentence: 'Coal, oil, and natural gas are ___ fuels.', answer: 'fossil', wrong: ['renewable', 'solar', 'nuclear'] },
  { id: 'sci-4-034', band: 4, sentence: 'The energy of a moving object is called ___ energy.', answer: 'kinetic', wrong: ['potential', 'solar', 'chemical'] },
  { id: 'sci-4-035', band: 4, sentence: 'A battery stores ___ energy.', answer: 'chemical', wrong: ['kinetic', 'light', 'sound'] },
  { id: 'sci-4-036', band: 4, sentence: 'A lever, a pulley, and a ramp are simple ___.', answer: 'machines', wrong: ['circuits', 'magnets', 'forces'] },
  { id: 'sci-4-037', band: 4, sentence: 'Heat moves from ___ objects to colder ones.', answer: 'warmer', wrong: ['smaller', 'darker', 'heavier'] },
  { id: 'sci-4-038', band: 4, sentence: 'A material that lets light pass through clearly is ___.', answer: 'transparent', wrong: ['opaque', 'magnetic', 'flexible'] },
  { id: 'sci-4-039', band: 4, sentence: 'Objects that block all light are ___.', answer: 'opaque', wrong: ['transparent', 'translucent', 'liquid'] },
  { id: 'sci-4-040', band: 4, sentence: 'Objects float in water when they are ___ than water.', answer: 'less dense', wrong: ['denser', 'hotter', 'larger'] },

  // Band 5: elements and atoms, acids, cells and DNA, units, surprising facts
  { id: 'sci-5-001', band: 5, sentence: 'The chemical symbol for gold is ___.', answer: 'Au', wrong: ['Ag', 'Fe', 'Pb'] },
  { id: 'sci-5-002', band: 5, sentence: 'The chemical symbol for iron is ___.', answer: 'Fe', wrong: ['Ir', 'In', 'I'] },
  { id: 'sci-5-003', band: 5, sentence: 'The chemical symbol for sodium is ___.', answer: 'Na', wrong: ['S', 'Sn', 'K'] },
  { id: 'sci-5-004', band: 5, sentence: 'H₂O is the chemical formula for ___.', answer: 'water', wrong: ['salt', 'oxygen', 'hydrogen'] },
  { id: 'sci-5-005', band: 5, sentence: 'CO₂ is the chemical formula for ___.', answer: 'carbon dioxide', wrong: ['oxygen', 'water', 'carbon monoxide'] },
  { id: 'sci-5-006', band: 5, sentence: 'Table salt is the compound sodium ___.', answer: 'chloride', wrong: ['carbonate', 'oxide', 'hydroxide'] },
  { id: 'sci-5-007', band: 5, sentence: "The most common gas in Earth's air is ___.", answer: 'nitrogen', wrong: ['oxygen', 'carbon dioxide', 'hydrogen'] },
  { id: 'sci-5-008', band: 5, sentence: 'Substances made of a single kind of atom are ___.', answer: 'elements', wrong: ['compounds', 'mixtures', 'solutions'] },
  { id: 'sci-5-009', band: 5, sentence: 'The center of an atom is called the ___.', answer: 'nucleus', wrong: ['electron', 'molecule', 'cell'] },
  { id: 'sci-5-010', band: 5, sentence: 'The nucleus of a carbon atom has protons and ___.', answer: 'neutrons', wrong: ['electrons', 'photons', 'molecules'] },
  { id: 'sci-5-011', band: 5, sentence: 'Tiny negatively charged particles in atoms are ___.', answer: 'electrons', wrong: ['protons', 'neutrons', 'nuclei'] },
  { id: 'sci-5-012', band: 5, sentence: 'Substances with a pH below 7 are ___.', answer: 'acids', wrong: ['bases', 'metals', 'gases'] },
  { id: 'sci-5-013', band: 5, sentence: 'At room temperature, pure water has a pH of ___.', answer: '7', wrong: ['1', '14', '10'] },
  { id: 'sci-5-014', band: 5, sentence: 'In plant and animal cells, the ___ controls the cell.', answer: 'nucleus', wrong: ['cell wall', 'ribosome', 'vacuole'] },
  { id: 'sci-5-015', band: 5, sentence: 'Our cells release most energy from food in their ___.', answer: 'mitochondria', wrong: ['nuclei', 'cell walls', 'vacuoles'] },
  { id: 'sci-5-016', band: 5, sentence: 'Plant cells have a ___ that animal cells do not.', answer: 'cell wall', wrong: ['nucleus', 'cell membrane', 'mitochondrion'] },
  { id: 'sci-5-017', band: 5, sentence: 'Plants carry out photosynthesis in their ___.', answer: 'chloroplasts', wrong: ['mitochondria', 'nuclei', 'vacuoles'] },
  { id: 'sci-5-018', band: 5, sentence: 'The genetic instructions in our cells are stored in ___.', answer: 'DNA', wrong: ['ATP', 'sugar', 'fat'] },
  { id: 'sci-5-019', band: 5, sentence: 'Genes are found on ___ in the nucleus.', answer: 'chromosomes', wrong: ['ribosomes', 'vacuoles', 'membranes'] },
  { id: 'sci-5-020', band: 5, sentence: 'Red blood cells carry ___ around the body.', answer: 'oxygen', wrong: ['nitrogen', 'food', 'germs'] },
  { id: 'sci-5-021', band: 5, sentence: 'White blood cells help the body fight ___.', answer: 'infections', wrong: ['gravity', 'thirst', 'sunlight'] },
  { id: 'sci-5-022', band: 5, sentence: 'The largest organ of the human body is the ___.', answer: 'skin', wrong: ['liver', 'heart', 'brain'] },
  { id: 'sci-5-023', band: 5, sentence: "The loss of water from a plant's leaves is called ___.", answer: 'transpiration', wrong: ['respiration', 'pollination', 'germination'] },
  { id: 'sci-5-024', band: 5, sentence: 'The SI unit of force is the ___.', answer: 'newton', wrong: ['joule', 'watt', 'meter'] },
  { id: 'sci-5-025', band: 5, sentence: 'The SI unit of energy is the ___.', answer: 'joule', wrong: ['newton', 'watt', 'volt'] },
  { id: 'sci-5-026', band: 5, sentence: 'The SI unit of power is the ___.', answer: 'watt', wrong: ['joule', 'newton', 'volt'] },
  { id: 'sci-5-027', band: 5, sentence: 'Of the planets around our Sun, ___ has the hottest surface.', answer: 'Venus', wrong: ['Mercury', 'Mars', 'Earth'] },
  { id: 'sci-5-028', band: 5, sentence: 'Light from the Sun takes about 8 ___ to reach Earth.', answer: 'minutes', wrong: ['seconds', 'hours', 'days'] },
  { id: 'sci-5-029', band: 5, sentence: 'A light-year is a unit of ___.', answer: 'distance', wrong: ['time', 'speed', 'brightness'] },
  { id: 'sci-5-030', band: 5, sentence: 'Earth has seasons mainly because of its ___.', answer: 'tilted axis', wrong: ['varying distance', 'spinning', 'Moon'] },
  { id: 'sci-5-031', band: 5, sentence: 'Tides in the ocean are caused mainly by the ___.', answer: 'Moon', wrong: ['wind', 'Sun', 'rivers'] },
  { id: 'sci-5-032', band: 5, sentence: 'Sound usually travels fastest through ___.', answer: 'solids', wrong: ['liquids', 'gases', 'empty space'] },
  { id: 'sci-5-033', band: 5, sentence: 'On the Moon, your ___ would be the same as on Earth.', answer: 'mass', wrong: ['weight', 'jump height', 'fall speed'] },
  { id: 'sci-5-034', band: 5, sentence: "A camel's hump stores ___.", answer: 'fat', wrong: ['water', 'milk', 'air'] },
  { id: 'sci-5-035', band: 5, sentence: 'Many bats find food in the dark using ___.', answer: 'echolocation', wrong: ['photosynthesis', 'magnetism', 'hibernation'] },
  { id: 'sci-5-036', band: 5, sentence: 'Diamonds and graphite are both made of ___.', answer: 'carbon', wrong: ['silicon', 'iron', 'quartz'] },
  { id: 'sci-5-037', band: 5, sentence: 'The Sun is mostly made of ___.', answer: 'hydrogen', wrong: ['oxygen', 'iron', 'carbon'] },
  { id: 'sci-5-038', band: 5, sentence: 'Water expands when it freezes, so ice ___ on water.', answer: 'floats', wrong: ['sinks', 'shrinks', 'dissolves'] },
  { id: 'sci-5-039', band: 5, sentence: 'An octopus has ___ hearts.', answer: '3', wrong: ['2', '4', '8'] },
  { id: 'sci-5-040', band: 5, sentence: 'The speed of light is about 300,000 ___ per second.', answer: 'kilometers', wrong: ['meters', 'miles', 'feet'] },
];
